// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbpeople

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Person struct {
	ID          int64
	FullName    string
	GivenName   sql.NullString
	FamilyName  sql.NullString
	DateOfBirth sql.NullTime
	Gender      sql.NullString
	Email       sql.NullString
	Phone       sql.NullString
	Metadata    json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Staff struct {
	ID          int64
	PersonID    int64
	ScopeNodeID int64
	Position    sql.NullString
	StaffCode   sql.NullString
	HireDate    sql.NullTime
	Metadata    json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Student struct {
	ID             int64
	PersonID       int64
	InstitutionID  int64
	StudentCode    sql.NullString
	EnrollmentDate sql.NullTime
	Metadata       json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}
