// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package dbpeople

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const CreatePerson = `-- name: CreatePerson :one
INSERT INTO persons (full_name, given_name, family_name, date_of_birth, gender, email, phone, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, full_name, given_name, family_name, date_of_birth, gender, email, phone, metadata, created_at, updated_at, deleted_at
`

type CreatePersonParams struct {
	FullName    string
	GivenName   sql.NullString
	FamilyName  sql.NullString
	DateOfBirth sql.NullTime
	Gender      sql.NullString
	Email       sql.NullString
	Phone       sql.NullString
	Metadata    json.RawMessage
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, CreatePerson,
		arg.FullName,
		arg.GivenName,
		arg.FamilyName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Email,
		arg.Phone,
		arg.Metadata,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.GivenName,
		&i.FamilyName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Email,
		&i.Phone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const CreateStaff = `-- name: CreateStaff :one
INSERT INTO staff (person_id, scope_node_id, position, staff_code, hire_date, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, person_id, scope_node_id, position, staff_code, hire_date, metadata, created_at, updated_at, deleted_at
`

type CreateStaffParams struct {
	PersonID    int64
	ScopeNodeID int64
	Position    sql.NullString
	StaffCode   sql.NullString
	HireDate    sql.NullTime
	Metadata    json.RawMessage
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRowContext(ctx, CreateStaff,
		arg.PersonID,
		arg.ScopeNodeID,
		arg.Position,
		arg.StaffCode,
		arg.HireDate,
		arg.Metadata,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ScopeNodeID,
		&i.Position,
		&i.StaffCode,
		&i.HireDate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const CreateStudent = `-- name: CreateStudent :one
INSERT INTO students (person_id, institution_id, student_code, enrollment_date, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, person_id, institution_id, student_code, enrollment_date, metadata, created_at, updated_at, deleted_at
`

type CreateStudentParams struct {
	PersonID       int64
	InstitutionID  int64
	StudentCode    sql.NullString
	EnrollmentDate sql.NullTime
	Metadata       json.RawMessage
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, CreateStudent,
		arg.PersonID,
		arg.InstitutionID,
		arg.StudentCode,
		arg.EnrollmentDate,
		arg.Metadata,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.InstitutionID,
		&i.StudentCode,
		&i.EnrollmentDate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetPersonByEmail = `-- name: GetPersonByEmail :one
SELECT id, full_name, given_name, family_name, date_of_birth, gender, email, phone, metadata, created_at, updated_at, deleted_at FROM persons
WHERE lower(email) = lower($1) AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPersonByEmail(ctx context.Context, lower string) (Person, error) {
	row := q.db.QueryRowContext(ctx, GetPersonByEmail, lower)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.GivenName,
		&i.FamilyName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Email,
		&i.Phone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetPersonByID = `-- name: GetPersonByID :one
SELECT id, full_name, given_name, family_name, date_of_birth, gender, email, phone, metadata, created_at, updated_at, deleted_at FROM persons WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPersonByID(ctx context.Context, id int64) (Person, error) {
	row := q.db.QueryRowContext(ctx, GetPersonByID, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.GivenName,
		&i.FamilyName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Email,
		&i.Phone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetSchoolsForStudents = `-- name: GetSchoolsForStudents :many
SELECT id AS student_id, institution_id
FROM students
WHERE id = ANY($1::bigint[]) AND deleted_at IS NULL
`

type GetSchoolsForStudentsRow struct {
	StudentID     int64
	InstitutionID int64
}

func (q *Queries) GetSchoolsForStudents(ctx context.Context, studentIds []int64) ([]GetSchoolsForStudentsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetSchoolsForStudents, pq.Array(studentIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSchoolsForStudentsRow{}
	for rows.Next() {
		var i GetSchoolsForStudentsRow
		if err := rows.Scan(&i.StudentID, &i.InstitutionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetStaffByID = `-- name: GetStaffByID :one
SELECT id, person_id, scope_node_id, position, staff_code, hire_date, metadata, created_at, updated_at, deleted_at FROM staff WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStaffByID(ctx context.Context, id int64) (Staff, error) {
	row := q.db.QueryRowContext(ctx, GetStaffByID, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ScopeNodeID,
		&i.Position,
		&i.StaffCode,
		&i.HireDate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetStudentByID = `-- name: GetStudentByID :one
SELECT id, person_id, institution_id, student_code, enrollment_date, metadata, created_at, updated_at, deleted_at FROM students WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStudentByID(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRowContext(ctx, GetStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.InstitutionID,
		&i.StudentCode,
		&i.EnrollmentDate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetStudentGendersByIDs = `-- name: GetStudentGendersByIDs :many
SELECT s.id AS student_id, p.gender
FROM students s
JOIN persons p ON p.id = s.person_id
WHERE s.id = ANY($1::bigint[])
  AND s.deleted_at IS NULL
  AND p.deleted_at IS NULL
`

type GetStudentGendersByIDsRow struct {
	StudentID int64
	Gender    sql.NullString
}

func (q *Queries) GetStudentGendersByIDs(ctx context.Context, studentIds []int64) ([]GetStudentGendersByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetStudentGendersByIDs, pq.Array(studentIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentGendersByIDsRow{}
	for rows.Next() {
		var i GetStudentGendersByIDsRow
		if err := rows.Scan(&i.StudentID, &i.Gender); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListStaffByPersonID = `-- name: ListStaffByPersonID :many
SELECT id, person_id, scope_node_id, position, staff_code, hire_date, metadata, created_at, updated_at, deleted_at FROM staff
WHERE person_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListStaffByPersonID(ctx context.Context, personID int64) ([]Staff, error) {
	rows, err := q.db.QueryContext(ctx, ListStaffByPersonID, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.ScopeNodeID,
			&i.Position,
			&i.StaffCode,
			&i.HireDate,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListStaffByScope = `-- name: ListStaffByScope :many
SELECT id, person_id, scope_node_id, position, staff_code, hire_date, metadata, created_at, updated_at, deleted_at FROM staff
WHERE scope_node_id = $1 AND deleted_at IS NULL
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListStaffByScopeParams struct {
	ScopeNodeID int64
	Limit       int32
	Offset      int32
}

func (q *Queries) ListStaffByScope(ctx context.Context, arg ListStaffByScopeParams) ([]Staff, error) {
	rows, err := q.db.QueryContext(ctx, ListStaffByScope, arg.ScopeNodeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.ScopeNodeID,
			&i.Position,
			&i.StaffCode,
			&i.HireDate,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListStaffByScopes = `-- name: ListStaffByScopes :many
SELECT id, person_id, scope_node_id, position, staff_code, hire_date, metadata, created_at, updated_at, deleted_at FROM staff
WHERE scope_node_id = ANY($1::bigint[]) AND deleted_at IS NULL
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListStaffByScopesParams struct {
	Column1 []int64
	Limit   int32
	Offset  int32
}

func (q *Queries) ListStaffByScopes(ctx context.Context, arg ListStaffByScopesParams) ([]Staff, error) {
	rows, err := q.db.QueryContext(ctx, ListStaffByScopes, pq.Array(arg.Column1), arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.ScopeNodeID,
			&i.Position,
			&i.StaffCode,
			&i.HireDate,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListStudentsByInstitution = `-- name: ListStudentsByInstitution :many
SELECT id, person_id, institution_id, student_code, enrollment_date, metadata, created_at, updated_at, deleted_at FROM students
WHERE institution_id = $1 AND deleted_at IS NULL
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListStudentsByInstitutionParams struct {
	InstitutionID int64
	Limit         int32
	Offset        int32
}

func (q *Queries) ListStudentsByInstitution(ctx context.Context, arg ListStudentsByInstitutionParams) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, ListStudentsByInstitution, arg.InstitutionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.InstitutionID,
			&i.StudentCode,
			&i.EnrollmentDate,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListStudentsByInstitutionWithPerson = `-- name: ListStudentsByInstitutionWithPerson :many
SELECT
    s.id              AS student_id,
    s.person_id       AS person_id,
    s.institution_id  AS institution_id,
    s.student_code    AS student_code,
    s.enrollment_date AS enrollment_date,
    s.metadata        AS metadata,
    s.created_at      AS created_at,
    s.updated_at      AS updated_at,
    p.full_name       AS full_name,
    p.given_name      AS given_name,
    p.family_name     AS family_name,
    p.date_of_birth   AS date_of_birth,
    p.gender          AS gender,
    p.email           AS email,
    p.phone           AS phone,
    p.metadata        AS person_metadata
FROM students s
JOIN persons p ON p.id = s.person_id
WHERE s.institution_id = $1
  AND s.deleted_at IS NULL
  AND p.deleted_at IS NULL
ORDER BY s.id
LIMIT $2 OFFSET $3
`

type ListStudentsByInstitutionWithPersonParams struct {
	InstitutionID int64
	Limit         int32
	Offset        int32
}

type ListStudentsByInstitutionWithPersonRow struct {
	StudentID      int64
	PersonID       int64
	InstitutionID  int64
	StudentCode    sql.NullString
	EnrollmentDate sql.NullTime
	Metadata       json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
	FullName       string
	GivenName      sql.NullString
	FamilyName     sql.NullString
	DateOfBirth    sql.NullTime
	Gender         sql.NullString
	Email          sql.NullString
	Phone          sql.NullString
	PersonMetadata json.RawMessage
}

func (q *Queries) ListStudentsByInstitutionWithPerson(ctx context.Context, arg ListStudentsByInstitutionWithPersonParams) ([]ListStudentsByInstitutionWithPersonRow, error) {
	rows, err := q.db.QueryContext(ctx, ListStudentsByInstitutionWithPerson, arg.InstitutionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsByInstitutionWithPersonRow{}
	for rows.Next() {
		var i ListStudentsByInstitutionWithPersonRow
		if err := rows.Scan(
			&i.StudentID,
			&i.PersonID,
			&i.InstitutionID,
			&i.StudentCode,
			&i.EnrollmentDate,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.GivenName,
			&i.FamilyName,
			&i.DateOfBirth,
			&i.Gender,
			&i.Email,
			&i.Phone,
			&i.PersonMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListStudentsByInstitutions = `-- name: ListStudentsByInstitutions :many
SELECT id, person_id, institution_id, student_code, enrollment_date, metadata, created_at, updated_at, deleted_at FROM students
WHERE institution_id = ANY($1::bigint[]) AND deleted_at IS NULL
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListStudentsByInstitutionsParams struct {
	Column1 []int64
	Limit   int32
	Offset  int32
}

func (q *Queries) ListStudentsByInstitutions(ctx context.Context, arg ListStudentsByInstitutionsParams) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, ListStudentsByInstitutions, pq.Array(arg.Column1), arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.InstitutionID,
			&i.StudentCode,
			&i.EnrollmentDate,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeletePerson = `-- name: SoftDeletePerson :exec
UPDATE persons SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePerson(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, SoftDeletePerson, id)
	return err
}

const SoftDeleteStaff = `-- name: SoftDeleteStaff :exec
UPDATE staff SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteStaff(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, SoftDeleteStaff, id)
	return err
}

const SoftDeleteStudent = `-- name: SoftDeleteStudent :exec
UPDATE students SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteStudent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, SoftDeleteStudent, id)
	return err
}
