// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment.sql

package dbenrollment

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const CreateEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (student_id, institution_id, period_id, status, enrolled_on)
VALUES ($1, $2, $3, 'active', $4)
RETURNING id, student_id, institution_id, period_id, status, enrolled_on, ended_on, metadata, created_at, updated_at
`

type CreateEnrollmentParams struct {
	StudentID     int64
	InstitutionID int64
	PeriodID      int64
	EnrolledOn    time.Time
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, CreateEnrollment,
		arg.StudentID,
		arg.InstitutionID,
		arg.PeriodID,
		arg.EnrolledOn,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.InstitutionID,
		&i.PeriodID,
		&i.Status,
		&i.EnrolledOn,
		&i.EndedOn,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateEnrollmentEvent = `-- name: CreateEnrollmentEvent :one
INSERT INTO enrollment_events (enrollment_id, kind, from_institution_id, to_institution_id, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, enrollment_id, kind, from_institution_id, to_institution_id, note, occurred_at
`

type CreateEnrollmentEventParams struct {
	EnrollmentID      int64
	Kind              string
	FromInstitutionID sql.NullInt64
	ToInstitutionID   sql.NullInt64
	Note              sql.NullString
}

func (q *Queries) CreateEnrollmentEvent(ctx context.Context, arg CreateEnrollmentEventParams) (EnrollmentEvent, error) {
	row := q.db.QueryRowContext(ctx, CreateEnrollmentEvent,
		arg.EnrollmentID,
		arg.Kind,
		arg.FromInstitutionID,
		arg.ToInstitutionID,
		arg.Note,
	)
	var i EnrollmentEvent
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.Kind,
		&i.FromInstitutionID,
		&i.ToInstitutionID,
		&i.Note,
		&i.OccurredAt,
	)
	return i, err
}

const GetActiveEnrollment = `-- name: GetActiveEnrollment :one
SELECT id, student_id, institution_id, period_id, status, enrolled_on, ended_on, metadata, created_at, updated_at FROM enrollments
WHERE student_id = $1 AND period_id = $2 AND status = 'active'
`

type GetActiveEnrollmentParams struct {
	StudentID int64
	PeriodID  int64
}

func (q *Queries) GetActiveEnrollment(ctx context.Context, arg GetActiveEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, GetActiveEnrollment, arg.StudentID, arg.PeriodID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.InstitutionID,
		&i.PeriodID,
		&i.Status,
		&i.EnrolledOn,
		&i.EndedOn,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetEnrollmentByID = `-- name: GetEnrollmentByID :one
SELECT id, student_id, institution_id, period_id, status, enrolled_on, ended_on, metadata, created_at, updated_at FROM enrollments WHERE id = $1
`

func (q *Queries) GetEnrollmentByID(ctx context.Context, id int64) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, GetEnrollmentByID, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.InstitutionID,
		&i.PeriodID,
		&i.Status,
		&i.EnrolledOn,
		&i.EndedOn,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetLatestCoverageSnapshot = `-- name: GetLatestCoverageSnapshot :one
SELECT id, scope_node_id, period_id, campaign_id, total_enrolled, total_male, total_female, total_other, total_tested, snapshot_at FROM coverage_snapshots
WHERE scope_node_id = $1 AND period_id = $2 AND campaign_id IS NOT DISTINCT FROM $3
ORDER BY snapshot_at DESC
LIMIT 1
`

type GetLatestCoverageSnapshotParams struct {
	ScopeNodeID int64
	PeriodID    int64
	CampaignID  sql.NullInt64
}

func (q *Queries) GetLatestCoverageSnapshot(ctx context.Context, arg GetLatestCoverageSnapshotParams) (CoverageSnapshot, error) {
	row := q.db.QueryRowContext(ctx, GetLatestCoverageSnapshot, arg.ScopeNodeID, arg.PeriodID, arg.CampaignID)
	var i CoverageSnapshot
	err := row.Scan(
		&i.ID,
		&i.ScopeNodeID,
		&i.PeriodID,
		&i.CampaignID,
		&i.TotalEnrolled,
		&i.TotalMale,
		&i.TotalFemale,
		&i.TotalOther,
		&i.TotalTested,
		&i.SnapshotAt,
	)
	return i, err
}

const ListActiveEnrollmentsByInstitution = `-- name: ListActiveEnrollmentsByInstitution :many
SELECT id, student_id, institution_id, period_id, status, enrolled_on, ended_on, metadata, created_at, updated_at FROM enrollments
WHERE institution_id = $1 AND period_id = $2 AND status = 'active'
ORDER BY enrolled_on DESC, id DESC
`

type ListActiveEnrollmentsByInstitutionParams struct {
	InstitutionID int64
	PeriodID      int64
}

func (q *Queries) ListActiveEnrollmentsByInstitution(ctx context.Context, arg ListActiveEnrollmentsByInstitutionParams) ([]Enrollment, error) {
	rows, err := q.db.QueryContext(ctx, ListActiveEnrollmentsByInstitution, arg.InstitutionID, arg.PeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Enrollment{}
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.InstitutionID,
			&i.PeriodID,
			&i.Status,
			&i.EnrolledOn,
			&i.EndedOn,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListActiveStudentIDsForInstitutions = `-- name: ListActiveStudentIDsForInstitutions :many
SELECT student_id, institution_id FROM enrollments
WHERE institution_id = ANY($2::bigint[])
  AND period_id = $1
  AND status = 'active'
ORDER BY institution_id, student_id
`

type ListActiveStudentIDsForInstitutionsParams struct {
	PeriodID       int64
	InstitutionIds []int64
}

type ListActiveStudentIDsForInstitutionsRow struct {
	StudentID     int64
	InstitutionID int64
}

func (q *Queries) ListActiveStudentIDsForInstitutions(ctx context.Context, arg ListActiveStudentIDsForInstitutionsParams) ([]ListActiveStudentIDsForInstitutionsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListActiveStudentIDsForInstitutions, arg.PeriodID, pq.Array(arg.InstitutionIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveStudentIDsForInstitutionsRow{}
	for rows.Next() {
		var i ListActiveStudentIDsForInstitutionsRow
		if err := rows.Scan(&i.StudentID, &i.InstitutionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListEnrollmentEvents = `-- name: ListEnrollmentEvents :many
SELECT id, enrollment_id, kind, from_institution_id, to_institution_id, note, occurred_at FROM enrollment_events
WHERE enrollment_id = $1
ORDER BY occurred_at DESC, id DESC
`

func (q *Queries) ListEnrollmentEvents(ctx context.Context, enrollmentID int64) ([]EnrollmentEvent, error) {
	rows, err := q.db.QueryContext(ctx, ListEnrollmentEvents, enrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentEvent{}
	for rows.Next() {
		var i EnrollmentEvent
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.Kind,
			&i.FromInstitutionID,
			&i.ToInstitutionID,
			&i.Note,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListEnrollmentsByInstitution = `-- name: ListEnrollmentsByInstitution :many
SELECT id, student_id, institution_id, period_id, status, enrolled_on, ended_on, metadata, created_at, updated_at FROM enrollments
WHERE institution_id = $1 AND period_id = $2
ORDER BY status, enrolled_on DESC, id DESC
`

type ListEnrollmentsByInstitutionParams struct {
	InstitutionID int64
	PeriodID      int64
}

func (q *Queries) ListEnrollmentsByInstitution(ctx context.Context, arg ListEnrollmentsByInstitutionParams) ([]Enrollment, error) {
	rows, err := q.db.QueryContext(ctx, ListEnrollmentsByInstitution, arg.InstitutionID, arg.PeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Enrollment{}
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.InstitutionID,
			&i.PeriodID,
			&i.Status,
			&i.EnrolledOn,
			&i.EndedOn,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListEnrollmentsByStudent = `-- name: ListEnrollmentsByStudent :many
SELECT id, student_id, institution_id, period_id, status, enrolled_on, ended_on, metadata, created_at, updated_at FROM enrollments
WHERE student_id = $1
ORDER BY enrolled_on DESC, id DESC
`

func (q *Queries) ListEnrollmentsByStudent(ctx context.Context, studentID int64) ([]Enrollment, error) {
	rows, err := q.db.QueryContext(ctx, ListEnrollmentsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Enrollment{}
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.InstitutionID,
			&i.PeriodID,
			&i.Status,
			&i.EnrolledOn,
			&i.EndedOn,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetEnrollmentStatus = `-- name: SetEnrollmentStatus :one
UPDATE enrollments
SET status = $2, ended_on = $3, updated_at = now()
WHERE id = $1
RETURNING id, student_id, institution_id, period_id, status, enrolled_on, ended_on, metadata, created_at, updated_at
`

type SetEnrollmentStatusParams struct {
	ID      int64
	Status  string
	EndedOn sql.NullTime
}

func (q *Queries) SetEnrollmentStatus(ctx context.Context, arg SetEnrollmentStatusParams) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, SetEnrollmentStatus, arg.ID, arg.Status, arg.EndedOn)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.InstitutionID,
		&i.PeriodID,
		&i.Status,
		&i.EnrolledOn,
		&i.EndedOn,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpsertCoverageSnapshot = `-- name: UpsertCoverageSnapshot :one
INSERT INTO coverage_snapshots (scope_node_id, period_id, campaign_id, total_enrolled, total_male, total_female, total_other, total_tested)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, scope_node_id, period_id, campaign_id, total_enrolled, total_male, total_female, total_other, total_tested, snapshot_at
`

type UpsertCoverageSnapshotParams struct {
	ScopeNodeID   int64
	PeriodID      int64
	CampaignID    sql.NullInt64
	TotalEnrolled int32
	TotalMale     int32
	TotalFemale   int32
	TotalOther    int32
	TotalTested   int32
}

func (q *Queries) UpsertCoverageSnapshot(ctx context.Context, arg UpsertCoverageSnapshotParams) (CoverageSnapshot, error) {
	row := q.db.QueryRowContext(ctx, UpsertCoverageSnapshot,
		arg.ScopeNodeID,
		arg.PeriodID,
		arg.CampaignID,
		arg.TotalEnrolled,
		arg.TotalMale,
		arg.TotalFemale,
		arg.TotalOther,
		arg.TotalTested,
	)
	var i CoverageSnapshot
	err := row.Scan(
		&i.ID,
		&i.ScopeNodeID,
		&i.PeriodID,
		&i.CampaignID,
		&i.TotalEnrolled,
		&i.TotalMale,
		&i.TotalFemale,
		&i.TotalOther,
		&i.TotalTested,
		&i.SnapshotAt,
	)
	return i, err
}
