// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbenrollment

import (
	"database/sql"
	"encoding/json"
	"time"
)

type CoverageSnapshot struct {
	ID            int64
	ScopeNodeID   int64
	PeriodID      int64
	CampaignID    sql.NullInt64
	TotalEnrolled int32
	TotalMale     int32
	TotalFemale   int32
	TotalOther    int32
	TotalTested   int32
	SnapshotAt    time.Time
}

type Enrollment struct {
	ID            int64
	StudentID     int64
	InstitutionID int64
	PeriodID      int64
	Status        string
	EnrolledOn    time.Time
	EndedOn       sql.NullTime
	Metadata      json.RawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type EnrollmentEvent struct {
	ID                int64
	EnrollmentID      int64
	Kind              string
	FromInstitutionID sql.NullInt64
	ToInstitutionID   sql.NullInt64
	Note              sql.NullString
	OccurredAt        time.Time
}
