// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package dbimports

import (
	"context"
	"database/sql"
	"encoding/json"
)

const AddRowError = `-- name: AddRowError :exec
INSERT INTO import_row_errors (job_id, row_number, field, error, raw_data)
VALUES ($1, $2, $3, $4, $5)
`

type AddRowErrorParams struct {
	JobID     int64
	RowNumber int32
	Field     sql.NullString
	Error     string
	RawData   json.RawMessage
}

func (q *Queries) AddRowError(ctx context.Context, arg AddRowErrorParams) error {
	_, err := q.db.ExecContext(ctx, AddRowError,
		arg.JobID,
		arg.RowNumber,
		arg.Field,
		arg.Error,
		arg.RawData,
	)
	return err
}

const CreateJob = `-- name: CreateJob :one
INSERT INTO import_jobs (kind, institution_id, status, dry_run, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, kind, institution_id, status, total_rows, succeeded_rows, failed_rows, dry_run, summary, created_by, created_at, completed_at
`

type CreateJobParams struct {
	Kind          string
	InstitutionID sql.NullInt64
	Status        string
	DryRun        bool
	CreatedBy     sql.NullInt64
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (ImportJob, error) {
	row := q.db.QueryRowContext(ctx, CreateJob,
		arg.Kind,
		arg.InstitutionID,
		arg.Status,
		arg.DryRun,
		arg.CreatedBy,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.InstitutionID,
		&i.Status,
		&i.TotalRows,
		&i.SucceededRows,
		&i.FailedRows,
		&i.DryRun,
		&i.Summary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const GetJobByID = `-- name: GetJobByID :one
SELECT id, kind, institution_id, status, total_rows, succeeded_rows, failed_rows, dry_run, summary, created_by, created_at, completed_at FROM import_jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRowContext(ctx, GetJobByID, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.InstitutionID,
		&i.Status,
		&i.TotalRows,
		&i.SucceededRows,
		&i.FailedRows,
		&i.DryRun,
		&i.Summary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const ListJobs = `-- name: ListJobs :many
SELECT id, kind, institution_id, status, total_rows, succeeded_rows, failed_rows, dry_run, summary, created_by, created_at, completed_at FROM import_jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ImportJob, error) {
	rows, err := q.db.QueryContext(ctx, ListJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportJob{}
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.InstitutionID,
			&i.Status,
			&i.TotalRows,
			&i.SucceededRows,
			&i.FailedRows,
			&i.DryRun,
			&i.Summary,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRowErrors = `-- name: ListRowErrors :many
SELECT id, job_id, row_number, field, error, raw_data FROM import_row_errors
WHERE job_id = $1
ORDER BY row_number, id
LIMIT $2 OFFSET $3
`

type ListRowErrorsParams struct {
	JobID  int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListRowErrors(ctx context.Context, arg ListRowErrorsParams) ([]ImportRowError, error) {
	rows, err := q.db.QueryContext(ctx, ListRowErrors, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportRowError{}
	for rows.Next() {
		var i ImportRowError
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RowNumber,
			&i.Field,
			&i.Error,
			&i.RawData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateJobResult = `-- name: UpdateJobResult :one
UPDATE import_jobs
SET status = $2,
    total_rows = $3,
    succeeded_rows = $4,
    failed_rows = $5,
    summary = $6,
    completed_at = now()
WHERE id = $1
RETURNING id, kind, institution_id, status, total_rows, succeeded_rows, failed_rows, dry_run, summary, created_by, created_at, completed_at
`

type UpdateJobResultParams struct {
	ID            int64
	Status        string
	TotalRows     int32
	SucceededRows int32
	FailedRows    int32
	Summary       json.RawMessage
}

func (q *Queries) UpdateJobResult(ctx context.Context, arg UpdateJobResultParams) (ImportJob, error) {
	row := q.db.QueryRowContext(ctx, UpdateJobResult,
		arg.ID,
		arg.Status,
		arg.TotalRows,
		arg.SucceededRows,
		arg.FailedRows,
		arg.Summary,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.InstitutionID,
		&i.Status,
		&i.TotalRows,
		&i.SucceededRows,
		&i.FailedRows,
		&i.DryRun,
		&i.Summary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
