// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbimports

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ImportJob struct {
	ID            int64
	Kind          string
	InstitutionID sql.NullInt64
	Status        string
	TotalRows     int32
	SucceededRows int32
	FailedRows    int32
	DryRun        bool
	Summary       json.RawMessage
	CreatedBy     sql.NullInt64
	CreatedAt     time.Time
	CompletedAt   sql.NullTime
}

type ImportRowError struct {
	ID        int64
	JobID     int64
	RowNumber int32
	Field     sql.NullString
	Error     string
	RawData   json.RawMessage
}
