// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsetup

import (
	"database/sql"
	"encoding/json"
	"time"
)

type SetupProgress struct {
	StepCode    string
	Payload     json.RawMessage
	CompletedAt sql.NullTime
	SkippedAt   sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SetupSession struct {
	TokenHash []byte
	ExpiresAt time.Time
	CreatedAt time.Time
}

type SystemSetting struct {
	Key       string
	Value     json.RawMessage
	UpdatedAt time.Time
}
