// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup.sql

package dbsetup

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const ConsumeInstallToken = `-- name: ConsumeInstallToken :exec
UPDATE setup_state
SET install_token_consumed_at = now(),
    updated_at                = now()
WHERE singleton = TRUE
  AND install_token_consumed_at IS NULL
`

func (q *Queries) ConsumeInstallToken(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ConsumeInstallToken)
	return err
}

const CreateSetupSession = `-- name: CreateSetupSession :exec
INSERT INTO setup_sessions (token_hash, expires_at)
VALUES ($1, $2)
`

type CreateSetupSessionParams struct {
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateSetupSession(ctx context.Context, arg CreateSetupSessionParams) error {
	_, err := q.db.ExecContext(ctx, CreateSetupSession, arg.TokenHash, arg.ExpiresAt)
	return err
}

const DeleteExpiredSetupSessions = `-- name: DeleteExpiredSetupSessions :exec
DELETE FROM setup_sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSetupSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteExpiredSetupSessions)
	return err
}

const GetSetupProgressStep = `-- name: GetSetupProgressStep :one
SELECT step_code, payload, completed_at, skipped_at, created_at, updated_at
FROM setup_progress WHERE step_code = $1
`

func (q *Queries) GetSetupProgressStep(ctx context.Context, stepCode string) (SetupProgress, error) {
	row := q.db.QueryRowContext(ctx, GetSetupProgressStep, stepCode)
	var i SetupProgress
	err := row.Scan(
		&i.StepCode,
		&i.Payload,
		&i.CompletedAt,
		&i.SkippedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetSetupSessionByHash = `-- name: GetSetupSessionByHash :one
SELECT token_hash, expires_at, created_at
FROM setup_sessions WHERE token_hash = $1
`

func (q *Queries) GetSetupSessionByHash(ctx context.Context, tokenHash []byte) (SetupSession, error) {
	row := q.db.QueryRowContext(ctx, GetSetupSessionByHash, tokenHash)
	var i SetupSession
	err := row.Scan(&i.TokenHash, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const GetSetupState = `-- name: GetSetupState :one
SELECT install_token_hash, install_token_consumed_at, failed_unlock_attempts,
       setup_complete_at, created_at, updated_at
FROM setup_state WHERE singleton = TRUE
`

type GetSetupStateRow struct {
	InstallTokenHash       sql.NullString
	InstallTokenConsumedAt sql.NullTime
	FailedUnlockAttempts   int32
	SetupCompleteAt        sql.NullTime
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) GetSetupState(ctx context.Context) (GetSetupStateRow, error) {
	row := q.db.QueryRowContext(ctx, GetSetupState)
	var i GetSetupStateRow
	err := row.Scan(
		&i.InstallTokenHash,
		&i.InstallTokenConsumedAt,
		&i.FailedUnlockAttempts,
		&i.SetupCompleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, updated_at
FROM system_settings WHERE key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, GetSystemSetting, key)
	var i SystemSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const IncrementFailedUnlockAttempts = `-- name: IncrementFailedUnlockAttempts :exec
UPDATE setup_state
SET failed_unlock_attempts = failed_unlock_attempts + 1,
    updated_at             = now()
WHERE singleton = TRUE
`

func (q *Queries) IncrementFailedUnlockAttempts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, IncrementFailedUnlockAttempts)
	return err
}

const ListSetupProgress = `-- name: ListSetupProgress :many
SELECT step_code, payload, completed_at, skipped_at, created_at, updated_at
FROM setup_progress
ORDER BY step_code
`

func (q *Queries) ListSetupProgress(ctx context.Context) ([]SetupProgress, error) {
	rows, err := q.db.QueryContext(ctx, ListSetupProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetupProgress{}
	for rows.Next() {
		var i SetupProgress
		if err := rows.Scan(
			&i.StepCode,
			&i.Payload,
			&i.CompletedAt,
			&i.SkippedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkSetupComplete = `-- name: MarkSetupComplete :exec
UPDATE setup_state
SET setup_complete_at = now(),
    updated_at        = now()
WHERE singleton = TRUE
  AND setup_complete_at IS NULL
`

func (q *Queries) MarkSetupComplete(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, MarkSetupComplete)
	return err
}

const ResetFailedUnlockAttempts = `-- name: ResetFailedUnlockAttempts :exec
UPDATE setup_state
SET failed_unlock_attempts = 0,
    updated_at             = now()
WHERE singleton = TRUE
`

func (q *Queries) ResetFailedUnlockAttempts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ResetFailedUnlockAttempts)
	return err
}

const SetInstallTokenHash = `-- name: SetInstallTokenHash :exec
UPDATE setup_state
SET install_token_hash = $1,
    updated_at         = now()
WHERE singleton = TRUE
`

func (q *Queries) SetInstallTokenHash(ctx context.Context, installTokenHash sql.NullString) error {
	_, err := q.db.ExecContext(ctx, SetInstallTokenHash, installTokenHash)
	return err
}

const UpsertSetupProgressComplete = `-- name: UpsertSetupProgressComplete :exec
INSERT INTO setup_progress (step_code, payload, completed_at)
VALUES ($1, $2, now())
ON CONFLICT (step_code) DO UPDATE
SET payload      = EXCLUDED.payload,
    completed_at = now(),
    skipped_at   = NULL,
    updated_at   = now()
`

type UpsertSetupProgressCompleteParams struct {
	StepCode string
	Payload  json.RawMessage
}

func (q *Queries) UpsertSetupProgressComplete(ctx context.Context, arg UpsertSetupProgressCompleteParams) error {
	_, err := q.db.ExecContext(ctx, UpsertSetupProgressComplete, arg.StepCode, arg.Payload)
	return err
}

const UpsertSetupProgressSkip = `-- name: UpsertSetupProgressSkip :exec
INSERT INTO setup_progress (step_code, payload, skipped_at)
VALUES ($1, '{}'::jsonb, now())
ON CONFLICT (step_code) DO UPDATE
SET skipped_at   = now(),
    completed_at = NULL,
    updated_at   = now()
`

func (q *Queries) UpsertSetupProgressSkip(ctx context.Context, stepCode string) error {
	_, err := q.db.ExecContext(ctx, UpsertSetupProgressSkip, stepCode)
	return err
}

const UpsertSystemSetting = `-- name: UpsertSystemSetting :exec
INSERT INTO system_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value      = EXCLUDED.value,
    updated_at = now()
`

type UpsertSystemSettingParams struct {
	Key   string
	Value json.RawMessage
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) error {
	_, err := q.db.ExecContext(ctx, UpsertSystemSetting, arg.Key, arg.Value)
	return err
}
