// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package dbai

import (
	"context"
	"database/sql"
	"encoding/json"
)

const CompleteJob = `-- name: CompleteJob :exec
UPDATE ai_jobs
SET status = 'done',
    completed_at = now(),
    request_tokens = $2,
    response_tokens = $3,
    latency_ms = $4
WHERE id = $1
`

type CompleteJobParams struct {
	ID             int64
	RequestTokens  int32
	ResponseTokens int32
	LatencyMs      int32
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, CompleteJob,
		arg.ID,
		arg.RequestTokens,
		arg.ResponseTokens,
		arg.LatencyMs,
	)
	return err
}

const CreateJob = `-- name: CreateJob :one
INSERT INTO ai_jobs (kind, model, prompt_summary, requested_by, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, kind, model, status, prompt_summary, request_tokens, response_tokens, latency_ms, error, requested_by, metadata, created_at, completed_at
`

type CreateJobParams struct {
	Kind          string
	Model         string
	PromptSummary string
	RequestedBy   sql.NullInt64
	Metadata      json.RawMessage
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (AiJob, error) {
	row := q.db.QueryRowContext(ctx, CreateJob,
		arg.Kind,
		arg.Model,
		arg.PromptSummary,
		arg.RequestedBy,
		arg.Metadata,
	)
	var i AiJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Model,
		&i.Status,
		&i.PromptSummary,
		&i.RequestTokens,
		&i.ResponseTokens,
		&i.LatencyMs,
		&i.Error,
		&i.RequestedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const FailJob = `-- name: FailJob :exec
UPDATE ai_jobs
SET status = 'failed',
    completed_at = now(),
    error = $2,
    latency_ms = $3
WHERE id = $1
`

type FailJobParams struct {
	ID        int64
	Error     sql.NullString
	LatencyMs int32
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, FailJob, arg.ID, arg.Error, arg.LatencyMs)
	return err
}

const GetJobByID = `-- name: GetJobByID :one
SELECT id, kind, model, status, prompt_summary, request_tokens, response_tokens, latency_ms, error, requested_by, metadata, created_at, completed_at FROM ai_jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id int64) (AiJob, error) {
	row := q.db.QueryRowContext(ctx, GetJobByID, id)
	var i AiJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Model,
		&i.Status,
		&i.PromptSummary,
		&i.RequestTokens,
		&i.ResponseTokens,
		&i.LatencyMs,
		&i.Error,
		&i.RequestedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const ListRecentJobs = `-- name: ListRecentJobs :many
SELECT id, kind, model, status, prompt_summary, request_tokens, response_tokens, latency_ms, error, requested_by, metadata, created_at, completed_at FROM ai_jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentJobsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRecentJobs(ctx context.Context, arg ListRecentJobsParams) ([]AiJob, error) {
	rows, err := q.db.QueryContext(ctx, ListRecentJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiJob{}
	for rows.Next() {
		var i AiJob
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Model,
			&i.Status,
			&i.PromptSummary,
			&i.RequestTokens,
			&i.ResponseTokens,
			&i.LatencyMs,
			&i.Error,
			&i.RequestedBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
