// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbai

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AiJob struct {
	ID             int64
	Kind           string
	Model          string
	Status         string
	PromptSummary  string
	RequestTokens  int32
	ResponseTokens int32
	LatencyMs      int32
	Error          sql.NullString
	RequestedBy    sql.NullInt64
	Metadata       json.RawMessage
	CreatedAt      time.Time
	CompletedAt    sql.NullTime
}
