// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbprogression

import (
	"database/sql"
	"time"
)

type ProgressionRefreshLog struct {
	ID          int64
	CampaignID  int64
	TriggeredAt time.Time
	CompletedAt sql.NullTime
	RowsWritten int32
	Error       sql.NullString
}

type ProgressionSnapshot struct {
	ID           int64
	ScopeNodeID  int64
	PeriodID     int64
	CampaignID   int64
	BandCode     string
	BandOrdinal  int32
	StudentCount int32
	SnapshotAt   time.Time
}
