// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progression.sql

package dbprogression

import (
	"context"
	"database/sql"
)

const CompleteRefreshLog = `-- name: CompleteRefreshLog :exec
UPDATE progression_refresh_log
SET completed_at = now(), rows_written = $2, error = $3
WHERE id = $1
`

type CompleteRefreshLogParams struct {
	ID          int64
	RowsWritten int32
	Error       sql.NullString
}

func (q *Queries) CompleteRefreshLog(ctx context.Context, arg CompleteRefreshLogParams) error {
	_, err := q.db.ExecContext(ctx, CompleteRefreshLog, arg.ID, arg.RowsWritten, arg.Error)
	return err
}

const CreateRefreshLog = `-- name: CreateRefreshLog :one
INSERT INTO progression_refresh_log (campaign_id)
VALUES ($1)
RETURNING id, campaign_id, triggered_at, completed_at, rows_written, error
`

func (q *Queries) CreateRefreshLog(ctx context.Context, campaignID int64) (ProgressionRefreshLog, error) {
	row := q.db.QueryRowContext(ctx, CreateRefreshLog, campaignID)
	var i ProgressionRefreshLog
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TriggeredAt,
		&i.CompletedAt,
		&i.RowsWritten,
		&i.Error,
	)
	return i, err
}

const DeleteSnapshotsForCampaign = `-- name: DeleteSnapshotsForCampaign :exec
DELETE FROM progression_snapshots
WHERE campaign_id = $1 AND period_id = $2
`

type DeleteSnapshotsForCampaignParams struct {
	CampaignID int64
	PeriodID   int64
}

func (q *Queries) DeleteSnapshotsForCampaign(ctx context.Context, arg DeleteSnapshotsForCampaignParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSnapshotsForCampaign, arg.CampaignID, arg.PeriodID)
	return err
}

const ListRecentRefreshes = `-- name: ListRecentRefreshes :many
SELECT id, campaign_id, triggered_at, completed_at, rows_written, error FROM progression_refresh_log
WHERE campaign_id = $1
ORDER BY triggered_at DESC
LIMIT $2
`

type ListRecentRefreshesParams struct {
	CampaignID int64
	Limit      int32
}

func (q *Queries) ListRecentRefreshes(ctx context.Context, arg ListRecentRefreshesParams) ([]ProgressionRefreshLog, error) {
	rows, err := q.db.QueryContext(ctx, ListRecentRefreshes, arg.CampaignID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgressionRefreshLog{}
	for rows.Next() {
		var i ProgressionRefreshLog
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.TriggeredAt,
			&i.CompletedAt,
			&i.RowsWritten,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSnapshotsForCampaign = `-- name: ListSnapshotsForCampaign :many
SELECT id, scope_node_id, period_id, campaign_id, band_code, band_ordinal, student_count, snapshot_at FROM progression_snapshots
WHERE campaign_id = $1 AND period_id = $2
ORDER BY scope_node_id, band_ordinal
`

type ListSnapshotsForCampaignParams struct {
	CampaignID int64
	PeriodID   int64
}

func (q *Queries) ListSnapshotsForCampaign(ctx context.Context, arg ListSnapshotsForCampaignParams) ([]ProgressionSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, ListSnapshotsForCampaign, arg.CampaignID, arg.PeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgressionSnapshot{}
	for rows.Next() {
		var i ProgressionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ScopeNodeID,
			&i.PeriodID,
			&i.CampaignID,
			&i.BandCode,
			&i.BandOrdinal,
			&i.StudentCount,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSnapshotsForScope = `-- name: ListSnapshotsForScope :many
SELECT id, scope_node_id, period_id, campaign_id, band_code, band_ordinal, student_count, snapshot_at FROM progression_snapshots
WHERE scope_node_id = $1 AND period_id = $2 AND campaign_id = $3
ORDER BY band_ordinal
`

type ListSnapshotsForScopeParams struct {
	ScopeNodeID int64
	PeriodID    int64
	CampaignID  int64
}

func (q *Queries) ListSnapshotsForScope(ctx context.Context, arg ListSnapshotsForScopeParams) ([]ProgressionSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, ListSnapshotsForScope, arg.ScopeNodeID, arg.PeriodID, arg.CampaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgressionSnapshot{}
	for rows.Next() {
		var i ProgressionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ScopeNodeID,
			&i.PeriodID,
			&i.CampaignID,
			&i.BandCode,
			&i.BandOrdinal,
			&i.StudentCount,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertSnapshot = `-- name: UpsertSnapshot :exec
INSERT INTO progression_snapshots (scope_node_id, period_id, campaign_id, band_code, band_ordinal, student_count)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (scope_node_id, period_id, campaign_id, band_code) DO UPDATE
SET student_count = EXCLUDED.student_count,
    band_ordinal = EXCLUDED.band_ordinal,
    snapshot_at = now()
`

type UpsertSnapshotParams struct {
	ScopeNodeID  int64
	PeriodID     int64
	CampaignID   int64
	BandCode     string
	BandOrdinal  int32
	StudentCount int32
}

func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, UpsertSnapshot,
		arg.ScopeNodeID,
		arg.PeriodID,
		arg.CampaignID,
		arg.BandCode,
		arg.BandOrdinal,
		arg.StudentCount,
	)
	return err
}
