// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hierarchy.sql

package dbtenancy

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const CreateHierarchyNode = `-- name: CreateHierarchyNode :one
INSERT INTO hierarchy_nodes (parent_id, level, code, label, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, parent_id, level, code, label, metadata, deleted_at, created_at, updated_at
`

type CreateHierarchyNodeParams struct {
	ParentID sql.NullInt64
	Level    string
	Code     string
	Label    string
	Metadata json.RawMessage
}

func (q *Queries) CreateHierarchyNode(ctx context.Context, arg CreateHierarchyNodeParams) (HierarchyNode, error) {
	row := q.db.QueryRowContext(ctx, CreateHierarchyNode,
		arg.ParentID,
		arg.Level,
		arg.Code,
		arg.Label,
		arg.Metadata,
	)
	var i HierarchyNode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Level,
		&i.Code,
		&i.Label,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAncestors = `-- name: GetAncestors :many
SELECT n.id, n.parent_id, n.level, n.code, n.label, n.metadata, n.deleted_at, n.created_at, n.updated_at, c.depth
FROM hierarchy_closure c
JOIN hierarchy_nodes n ON n.id = c.ancestor_id
WHERE c.descendant_id = $1 AND n.deleted_at IS NULL
ORDER BY c.depth DESC
`

type GetAncestorsRow struct {
	ID        int64
	ParentID  sql.NullInt64
	Level     string
	Code      string
	Label     string
	Metadata  json.RawMessage
	DeletedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
	Depth     int32
}

func (q *Queries) GetAncestors(ctx context.Context, descendantID int64) ([]GetAncestorsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetAncestors, descendantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAncestorsRow{}
	for rows.Next() {
		var i GetAncestorsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Level,
			&i.Code,
			&i.Label,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetDescendants = `-- name: GetDescendants :many
SELECT n.id, n.parent_id, n.level, n.code, n.label, n.metadata, n.deleted_at, n.created_at, n.updated_at, c.depth
FROM hierarchy_closure c
JOIN hierarchy_nodes n ON n.id = c.descendant_id
WHERE c.ancestor_id = $1 AND n.deleted_at IS NULL
ORDER BY c.depth, n.label
`

type GetDescendantsRow struct {
	ID        int64
	ParentID  sql.NullInt64
	Level     string
	Code      string
	Label     string
	Metadata  json.RawMessage
	DeletedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
	Depth     int32
}

func (q *Queries) GetDescendants(ctx context.Context, ancestorID int64) ([]GetDescendantsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetDescendants, ancestorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDescendantsRow{}
	for rows.Next() {
		var i GetDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Level,
			&i.Code,
			&i.Label,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetHierarchyNodeByID = `-- name: GetHierarchyNodeByID :one
SELECT id, parent_id, level, code, label, metadata, deleted_at, created_at, updated_at FROM hierarchy_nodes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetHierarchyNodeByID(ctx context.Context, id int64) (HierarchyNode, error) {
	row := q.db.QueryRowContext(ctx, GetHierarchyNodeByID, id)
	var i HierarchyNode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Level,
		&i.Code,
		&i.Label,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetHierarchyNodeParent = `-- name: GetHierarchyNodeParent :one
SELECT id, parent_id, level, code, label, metadata, deleted_at, created_at, updated_at FROM hierarchy_nodes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetHierarchyNodeParent(ctx context.Context, id int64) (HierarchyNode, error) {
	row := q.db.QueryRowContext(ctx, GetHierarchyNodeParent, id)
	var i HierarchyNode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Level,
		&i.Code,
		&i.Label,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const HasUndeletedChildren = `-- name: HasUndeletedChildren :one
SELECT EXISTS(
    SELECT 1 FROM hierarchy_nodes
    WHERE parent_id = $1 AND deleted_at IS NULL
) AS has_children
`

func (q *Queries) HasUndeletedChildren(ctx context.Context, parentID sql.NullInt64) (bool, error) {
	row := q.db.QueryRowContext(ctx, HasUndeletedChildren, parentID)
	var has_children bool
	err := row.Scan(&has_children)
	return has_children, err
}

const InsertClosureFromParent = `-- name: InsertClosureFromParent :exec
INSERT INTO hierarchy_closure (ancestor_id, descendant_id, depth)
SELECT ancestor_id, $2::bigint, depth + 1
FROM hierarchy_closure
WHERE descendant_id = $1::bigint
`

type InsertClosureFromParentParams struct {
	Column1 int64
	Column2 int64
}

func (q *Queries) InsertClosureFromParent(ctx context.Context, arg InsertClosureFromParentParams) error {
	_, err := q.db.ExecContext(ctx, InsertClosureFromParent, arg.Column1, arg.Column2)
	return err
}

const InsertSelfClosure = `-- name: InsertSelfClosure :exec
INSERT INTO hierarchy_closure (ancestor_id, descendant_id, depth)
VALUES ($1, $1, 0)
`

func (q *Queries) InsertSelfClosure(ctx context.Context, ancestorID int64) error {
	_, err := q.db.ExecContext(ctx, InsertSelfClosure, ancestorID)
	return err
}

const IsAncestorClosure = `-- name: IsAncestorClosure :one
SELECT EXISTS(
    SELECT 1 FROM hierarchy_closure
    WHERE ancestor_id = $1 AND descendant_id = $2
) AS is_ancestor
`

type IsAncestorClosureParams struct {
	AncestorID   int64
	DescendantID int64
}

func (q *Queries) IsAncestorClosure(ctx context.Context, arg IsAncestorClosureParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, IsAncestorClosure, arg.AncestorID, arg.DescendantID)
	var is_ancestor bool
	err := row.Scan(&is_ancestor)
	return is_ancestor, err
}

const ListAncestorIDs = `-- name: ListAncestorIDs :many
SELECT ancestor_id
FROM hierarchy_closure
WHERE descendant_id = $1
`

func (q *Queries) ListAncestorIDs(ctx context.Context, descendantID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, ListAncestorIDs, descendantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ancestor_id int64
		if err := rows.Scan(&ancestor_id); err != nil {
			return nil, err
		}
		items = append(items, ancestor_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAncestorIDsForMany = `-- name: ListAncestorIDsForMany :many
SELECT DISTINCT ancestor_id
FROM hierarchy_closure
WHERE descendant_id = ANY($1::bigint[])
`

func (q *Queries) ListAncestorIDsForMany(ctx context.Context, dollar_1 []int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, ListAncestorIDsForMany, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ancestor_id int64
		if err := rows.Scan(&ancestor_id); err != nil {
			return nil, err
		}
		items = append(items, ancestor_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDescendantIDs = `-- name: ListDescendantIDs :many
SELECT descendant_id
FROM hierarchy_closure
WHERE ancestor_id = $1
`

func (q *Queries) ListDescendantIDs(ctx context.Context, ancestorID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, ListDescendantIDs, ancestorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var descendant_id int64
		if err := rows.Scan(&descendant_id); err != nil {
			return nil, err
		}
		items = append(items, descendant_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListHierarchyNodesByLevel = `-- name: ListHierarchyNodesByLevel :many
SELECT id, parent_id, level, code, label, metadata, deleted_at, created_at, updated_at FROM hierarchy_nodes
WHERE level = $1 AND deleted_at IS NULL
ORDER BY label
`

func (q *Queries) ListHierarchyNodesByLevel(ctx context.Context, level string) ([]HierarchyNode, error) {
	rows, err := q.db.QueryContext(ctx, ListHierarchyNodesByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HierarchyNode{}
	for rows.Next() {
		var i HierarchyNode
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Level,
			&i.Code,
			&i.Label,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListHierarchyNodesByParent = `-- name: ListHierarchyNodesByParent :many
SELECT id, parent_id, level, code, label, metadata, deleted_at, created_at, updated_at FROM hierarchy_nodes
WHERE COALESCE(parent_id, 0) = COALESCE($1::bigint, 0) AND deleted_at IS NULL
ORDER BY label
`

func (q *Queries) ListHierarchyNodesByParent(ctx context.Context, dollar_1 int64) ([]HierarchyNode, error) {
	rows, err := q.db.QueryContext(ctx, ListHierarchyNodesByParent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HierarchyNode{}
	for rows.Next() {
		var i HierarchyNode
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Level,
			&i.Code,
			&i.Label,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeleteHierarchyNode = `-- name: SoftDeleteHierarchyNode :exec
UPDATE hierarchy_nodes
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteHierarchyNode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, SoftDeleteHierarchyNode, id)
	return err
}
