// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: levels.sql

package dbtenancy

import (
	"context"
	"database/sql"
)

const DeleteAllHierarchyLevels = `-- name: DeleteAllHierarchyLevels :exec
DELETE FROM hierarchy_levels
`

func (q *Queries) DeleteAllHierarchyLevels(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteAllHierarchyLevels)
	return err
}

const GetHierarchyLevel = `-- name: GetHierarchyLevel :one
SELECT code, label, parent_level_code, depth, sort_order, created_at, updated_at
FROM hierarchy_levels
WHERE code = $1
`

func (q *Queries) GetHierarchyLevel(ctx context.Context, code string) (HierarchyLevel, error) {
	row := q.db.QueryRowContext(ctx, GetHierarchyLevel, code)
	var i HierarchyLevel
	err := row.Scan(
		&i.Code,
		&i.Label,
		&i.ParentLevelCode,
		&i.Depth,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListHierarchyLevels = `-- name: ListHierarchyLevels :many
SELECT code, label, parent_level_code, depth, sort_order, created_at, updated_at
FROM hierarchy_levels
ORDER BY depth, sort_order, code
`

func (q *Queries) ListHierarchyLevels(ctx context.Context) ([]HierarchyLevel, error) {
	rows, err := q.db.QueryContext(ctx, ListHierarchyLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HierarchyLevel{}
	for rows.Next() {
		var i HierarchyLevel
		if err := rows.Scan(
			&i.Code,
			&i.Label,
			&i.ParentLevelCode,
			&i.Depth,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertHierarchyLevel = `-- name: UpsertHierarchyLevel :exec
INSERT INTO hierarchy_levels (code, label, parent_level_code, depth, sort_order)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (code) DO UPDATE
SET label             = EXCLUDED.label,
    parent_level_code = EXCLUDED.parent_level_code,
    depth             = EXCLUDED.depth,
    sort_order        = EXCLUDED.sort_order,
    updated_at        = now()
`

type UpsertHierarchyLevelParams struct {
	Code            string
	Label           string
	ParentLevelCode sql.NullString
	Depth           int32
	SortOrder       int32
}

func (q *Queries) UpsertHierarchyLevel(ctx context.Context, arg UpsertHierarchyLevelParams) error {
	_, err := q.db.ExecContext(ctx, UpsertHierarchyLevel,
		arg.Code,
		arg.Label,
		arg.ParentLevelCode,
		arg.Depth,
		arg.SortOrder,
	)
	return err
}
