// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbtenancy

import (
	"database/sql"
	"encoding/json"
	"time"
)

type HierarchyLevel struct {
	Code            string
	Label           string
	ParentLevelCode sql.NullString
	Depth           int32
	SortOrder       int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type HierarchyNode struct {
	ID        int64
	ParentID  sql.NullInt64
	Level     string
	Code      string
	Label     string
	Metadata  json.RawMessage
	DeletedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}
