// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: academics.sql

package dbacademics

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const AddStaffToClass = `-- name: AddStaffToClass :exec
INSERT INTO class_staff (class_id, staff_id, role)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddStaffToClassParams struct {
	ClassID int64
	StaffID int64
	Role    string
}

func (q *Queries) AddStaffToClass(ctx context.Context, arg AddStaffToClassParams) error {
	_, err := q.db.ExecContext(ctx, AddStaffToClass, arg.ClassID, arg.StaffID, arg.Role)
	return err
}

const AddStudentToClass = `-- name: AddStudentToClass :exec
INSERT INTO class_students (class_id, student_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddStudentToClassParams struct {
	ClassID   int64
	StudentID int64
}

func (q *Queries) AddStudentToClass(ctx context.Context, arg AddStudentToClassParams) error {
	_, err := q.db.ExecContext(ctx, AddStudentToClass, arg.ClassID, arg.StudentID)
	return err
}

const ClearCurrentPeriod = `-- name: ClearCurrentPeriod :exec
UPDATE academic_periods
SET is_current = FALSE, updated_at = now()
WHERE is_current = TRUE AND deleted_at IS NULL
`

func (q *Queries) ClearCurrentPeriod(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ClearCurrentPeriod)
	return err
}

const CreateClass = `-- name: CreateClass :one
INSERT INTO classes (period_id, niveau_id, institution_id, code, label, capacity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, period_id, niveau_id, institution_id, code, label, capacity, created_at, updated_at, deleted_at
`

type CreateClassParams struct {
	PeriodID      int64
	NiveauID      int64
	InstitutionID int64
	Code          string
	Label         string
	Capacity      sql.NullInt32
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, CreateClass,
		arg.PeriodID,
		arg.NiveauID,
		arg.InstitutionID,
		arg.Code,
		arg.Label,
		arg.Capacity,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.NiveauID,
		&i.InstitutionID,
		&i.Code,
		&i.Label,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const CreateNiveau = `-- name: CreateNiveau :one
INSERT INTO niveaux (code, label, sort_order)
VALUES ($1, $2, $3)
RETURNING id, code, label, sort_order, created_at, updated_at, deleted_at
`

type CreateNiveauParams struct {
	Code      string
	Label     string
	SortOrder int32
}

func (q *Queries) CreateNiveau(ctx context.Context, arg CreateNiveauParams) (Niveaux, error) {
	row := q.db.QueryRowContext(ctx, CreateNiveau, arg.Code, arg.Label, arg.SortOrder)
	var i Niveaux
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const CreatePeriod = `-- name: CreatePeriod :one
INSERT INTO academic_periods (code, label, starts_on, ends_on, is_current)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, label, starts_on, ends_on, is_current, created_at, updated_at, deleted_at
`

type CreatePeriodParams struct {
	Code      string
	Label     string
	StartsOn  time.Time
	EndsOn    time.Time
	IsCurrent bool
}

func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (AcademicPeriod, error) {
	row := q.db.QueryRowContext(ctx, CreatePeriod,
		arg.Code,
		arg.Label,
		arg.StartsOn,
		arg.EndsOn,
		arg.IsCurrent,
	)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetClassByID = `-- name: GetClassByID :one
SELECT id, period_id, niveau_id, institution_id, code, label, capacity, created_at, updated_at, deleted_at FROM classes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetClassByID(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRowContext(ctx, GetClassByID, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.NiveauID,
		&i.InstitutionID,
		&i.Code,
		&i.Label,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetCurrentPeriod = `-- name: GetCurrentPeriod :one
SELECT id, code, label, starts_on, ends_on, is_current, created_at, updated_at, deleted_at FROM academic_periods
WHERE is_current = TRUE AND deleted_at IS NULL
`

func (q *Queries) GetCurrentPeriod(ctx context.Context) (AcademicPeriod, error) {
	row := q.db.QueryRowContext(ctx, GetCurrentPeriod)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetNiveauByID = `-- name: GetNiveauByID :one
SELECT id, code, label, sort_order, created_at, updated_at, deleted_at FROM niveaux
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNiveauByID(ctx context.Context, id int64) (Niveaux, error) {
	row := q.db.QueryRowContext(ctx, GetNiveauByID, id)
	var i Niveaux
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetPeriodByCode = `-- name: GetPeriodByCode :one
SELECT id, code, label, starts_on, ends_on, is_current, created_at, updated_at, deleted_at FROM academic_periods
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPeriodByCode(ctx context.Context, code string) (AcademicPeriod, error) {
	row := q.db.QueryRowContext(ctx, GetPeriodByCode, code)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetPeriodByID = `-- name: GetPeriodByID :one
SELECT id, code, label, starts_on, ends_on, is_current, created_at, updated_at, deleted_at FROM academic_periods
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPeriodByID(ctx context.Context, id int64) (AcademicPeriod, error) {
	row := q.db.QueryRowContext(ctx, GetPeriodByID, id)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const IsClassStaff = `-- name: IsClassStaff :one
SELECT EXISTS(SELECT 1 FROM class_staff WHERE class_id = $1 AND staff_id = ANY($2::bigint[]))
`

type IsClassStaffParams struct {
	ClassID  int64
	StaffIds []int64
}

func (q *Queries) IsClassStaff(ctx context.Context, arg IsClassStaffParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, IsClassStaff, arg.ClassID, pq.Array(arg.StaffIds))
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ListClassStaff = `-- name: ListClassStaff :many
SELECT staff_id, role FROM class_staff
WHERE class_id = $1
ORDER BY role, staff_id
`

type ListClassStaffRow struct {
	StaffID int64
	Role    string
}

func (q *Queries) ListClassStaff(ctx context.Context, classID int64) ([]ListClassStaffRow, error) {
	rows, err := q.db.QueryContext(ctx, ListClassStaff, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassStaffRow{}
	for rows.Next() {
		var i ListClassStaffRow
		if err := rows.Scan(&i.StaffID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListClassStudents = `-- name: ListClassStudents :many
SELECT student_id FROM class_students
WHERE class_id = $1
ORDER BY student_id
`

func (q *Queries) ListClassStudents(ctx context.Context, classID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, ListClassStudents, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var student_id int64
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListClassesByInstitution = `-- name: ListClassesByInstitution :many
SELECT id, period_id, niveau_id, institution_id, code, label, capacity, created_at, updated_at, deleted_at FROM classes
WHERE institution_id = $1 AND deleted_at IS NULL
ORDER BY code ASC
`

func (q *Queries) ListClassesByInstitution(ctx context.Context, institutionID int64) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, ListClassesByInstitution, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.NiveauID,
			&i.InstitutionID,
			&i.Code,
			&i.Label,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListClassesByPeriod = `-- name: ListClassesByPeriod :many
SELECT id, period_id, niveau_id, institution_id, code, label, capacity, created_at, updated_at, deleted_at FROM classes
WHERE period_id = $1 AND deleted_at IS NULL
ORDER BY institution_id ASC, code ASC
`

func (q *Queries) ListClassesByPeriod(ctx context.Context, periodID int64) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, ListClassesByPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.NiveauID,
			&i.InstitutionID,
			&i.Code,
			&i.Label,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListClassesForAnyStaff = `-- name: ListClassesForAnyStaff :many
SELECT DISTINCT c.id, c.period_id, c.niveau_id, c.institution_id, c.code, c.label, c.capacity, c.created_at, c.updated_at, c.deleted_at FROM classes c
JOIN class_staff cst ON cst.class_id = c.id
WHERE cst.staff_id = ANY($1::bigint[]) AND c.deleted_at IS NULL
ORDER BY c.code
`

func (q *Queries) ListClassesForAnyStaff(ctx context.Context, staffIds []int64) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, ListClassesForAnyStaff, pq.Array(staffIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.NiveauID,
			&i.InstitutionID,
			&i.Code,
			&i.Label,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListClassesForStaff = `-- name: ListClassesForStaff :many
SELECT c.id, c.period_id, c.niveau_id, c.institution_id, c.code, c.label, c.capacity, c.created_at, c.updated_at, c.deleted_at FROM classes c
JOIN class_staff cst ON cst.class_id = c.id
WHERE cst.staff_id = $1 AND c.deleted_at IS NULL
ORDER BY c.code
`

func (q *Queries) ListClassesForStaff(ctx context.Context, staffID int64) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, ListClassesForStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.NiveauID,
			&i.InstitutionID,
			&i.Code,
			&i.Label,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListClassesForStudent = `-- name: ListClassesForStudent :many
SELECT c.id, c.period_id, c.niveau_id, c.institution_id, c.code, c.label, c.capacity, c.created_at, c.updated_at, c.deleted_at FROM classes c
JOIN class_students cs ON cs.class_id = c.id
WHERE cs.student_id = $1 AND c.deleted_at IS NULL
ORDER BY c.code
`

func (q *Queries) ListClassesForStudent(ctx context.Context, studentID int64) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, ListClassesForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.NiveauID,
			&i.InstitutionID,
			&i.Code,
			&i.Label,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListNiveaux = `-- name: ListNiveaux :many
SELECT id, code, label, sort_order, created_at, updated_at, deleted_at FROM niveaux
WHERE deleted_at IS NULL
ORDER BY sort_order ASC, code ASC
`

func (q *Queries) ListNiveaux(ctx context.Context) ([]Niveaux, error) {
	rows, err := q.db.QueryContext(ctx, ListNiveaux)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Niveaux{}
	for rows.Next() {
		var i Niveaux
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPeriods = `-- name: ListPeriods :many
SELECT id, code, label, starts_on, ends_on, is_current, created_at, updated_at, deleted_at FROM academic_periods
WHERE deleted_at IS NULL
ORDER BY starts_on DESC
`

func (q *Queries) ListPeriods(ctx context.Context) ([]AcademicPeriod, error) {
	rows, err := q.db.QueryContext(ctx, ListPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicPeriod{}
	for rows.Next() {
		var i AcademicPeriod
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.StartsOn,
			&i.EndsOn,
			&i.IsCurrent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveStaffFromClass = `-- name: RemoveStaffFromClass :exec
DELETE FROM class_staff
WHERE class_id = $1 AND staff_id = $2 AND role = $3
`

type RemoveStaffFromClassParams struct {
	ClassID int64
	StaffID int64
	Role    string
}

func (q *Queries) RemoveStaffFromClass(ctx context.Context, arg RemoveStaffFromClassParams) error {
	_, err := q.db.ExecContext(ctx, RemoveStaffFromClass, arg.ClassID, arg.StaffID, arg.Role)
	return err
}

const RemoveStudentFromClass = `-- name: RemoveStudentFromClass :exec
DELETE FROM class_students
WHERE class_id = $1 AND student_id = $2
`

type RemoveStudentFromClassParams struct {
	ClassID   int64
	StudentID int64
}

func (q *Queries) RemoveStudentFromClass(ctx context.Context, arg RemoveStudentFromClassParams) error {
	_, err := q.db.ExecContext(ctx, RemoveStudentFromClass, arg.ClassID, arg.StudentID)
	return err
}

const SetPeriodCurrent = `-- name: SetPeriodCurrent :one
UPDATE academic_periods
SET is_current = TRUE, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, label, starts_on, ends_on, is_current, created_at, updated_at, deleted_at
`

func (q *Queries) SetPeriodCurrent(ctx context.Context, id int64) (AcademicPeriod, error) {
	row := q.db.QueryRowContext(ctx, SetPeriodCurrent, id)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const SoftDeleteClass = `-- name: SoftDeleteClass :exec
UPDATE classes
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteClass(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, SoftDeleteClass, id)
	return err
}

const SoftDeleteNiveau = `-- name: SoftDeleteNiveau :exec
UPDATE niveaux
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteNiveau(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, SoftDeleteNiveau, id)
	return err
}

const SoftDeletePeriod = `-- name: SoftDeletePeriod :exec
UPDATE academic_periods
SET deleted_at = now(), is_current = FALSE, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePeriod(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, SoftDeletePeriod, id)
	return err
}
