// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbacademics

import (
	"database/sql"
	"time"
)

type AcademicPeriod struct {
	ID        int64
	Code      string
	Label     string
	StartsOn  time.Time
	EndsOn    time.Time
	IsCurrent bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Class struct {
	ID            int64
	PeriodID      int64
	NiveauID      int64
	InstitutionID int64
	Code          string
	Label         string
	Capacity      sql.NullInt32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type Niveaux struct {
	ID        int64
	Code      string
	Label     string
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
