// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"encore.app/apps/ai/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

func DraftRubric(ctx context.Context, question_title string, scale_code string, band_codes []string, opts ...CallOptionFunc) (types.RubricBandList, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"question_title": question_title, "scale_code": scale_code, "band_codes": band_codes},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "DraftRubric", encoded, callOpts.onTick)
		if err != nil {
			return types.RubricBandList{}, err
		}

		if result.Error != nil {
			return types.RubricBandList{}, result.Error
		}

		casted := (result.Data).(types.RubricBandList)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "DraftRubric", encoded, callOpts.onTick)
		if err != nil {
			return types.RubricBandList{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.RubricBandList{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.RubricBandList), nil
			}
		}

		return types.RubricBandList{}, fmt.Errorf("No data returned from stream")
	}
}

func GenerateDistractors(ctx context.Context, question_title string, correct_answer string, count int64, opts ...CallOptionFunc) (types.DistractorList, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"question_title": question_title, "correct_answer": correct_answer, "count": count},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateDistractors", encoded, callOpts.onTick)
		if err != nil {
			return types.DistractorList{}, err
		}

		if result.Error != nil {
			return types.DistractorList{}, result.Error
		}

		casted := (result.Data).(types.DistractorList)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateDistractors", encoded, callOpts.onTick)
		if err != nil {
			return types.DistractorList{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.DistractorList{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.DistractorList), nil
			}
		}

		return types.DistractorList{}, fmt.Errorf("No data returned from stream")
	}
}

func GradeEssay(ctx context.Context, question_title string, student_answer string, rubric []types.RubricBand, opts ...CallOptionFunc) (types.GradeResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"question_title": question_title, "student_answer": student_answer, "rubric": rubric},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GradeEssay", encoded, callOpts.onTick)
		if err != nil {
			return types.GradeResult{}, err
		}

		if result.Error != nil {
			return types.GradeResult{}, result.Error
		}

		casted := (result.Data).(types.GradeResult)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GradeEssay", encoded, callOpts.onTick)
		if err != nil {
			return types.GradeResult{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.GradeResult{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.GradeResult), nil
			}
		}

		return types.GradeResult{}, fmt.Errorf("No data returned from stream")
	}
}

func SuggestItems(ctx context.Context, topic string, scale_code string, niveau_label string, count int64, opts ...CallOptionFunc) (types.SuggestedItemList, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "scale_code": scale_code, "niveau_label": niveau_label, "count": count},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "SuggestItems", encoded, callOpts.onTick)
		if err != nil {
			return types.SuggestedItemList{}, err
		}

		if result.Error != nil {
			return types.SuggestedItemList{}, result.Error
		}

		casted := (result.Data).(types.SuggestedItemList)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "SuggestItems", encoded, callOpts.onTick)
		if err != nil {
			return types.SuggestedItemList{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.SuggestedItemList{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.SuggestedItemList), nil
			}
		}

		return types.SuggestedItemList{}, fmt.Errorf("No data returned from stream")
	}
}
