// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"encore.app/apps/ai/baml_client/stream_types"
	"encore.app/apps/ai/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.DistractorList":           reflect.TypeOf(types.DistractorList{}),
	"STREAM_TYPES.DistractorList":    reflect.TypeOf(stream_types.DistractorList{}),
	"TYPES.GradeResult":              reflect.TypeOf(types.GradeResult{}),
	"STREAM_TYPES.GradeResult":       reflect.TypeOf(stream_types.GradeResult{}),
	"TYPES.RubricBand":               reflect.TypeOf(types.RubricBand{}),
	"STREAM_TYPES.RubricBand":        reflect.TypeOf(stream_types.RubricBand{}),
	"TYPES.RubricBandList":           reflect.TypeOf(types.RubricBandList{}),
	"STREAM_TYPES.RubricBandList":    reflect.TypeOf(stream_types.RubricBandList{}),
	"TYPES.SuggestedItem":            reflect.TypeOf(types.SuggestedItem{}),
	"STREAM_TYPES.SuggestedItem":     reflect.TypeOf(stream_types.SuggestedItem{}),
	"TYPES.SuggestedItemList":        reflect.TypeOf(types.SuggestedItemList{}),
	"STREAM_TYPES.SuggestedItemList": reflect.TypeOf(stream_types.SuggestedItemList{}),

	"TYPES.QuestionType": reflect.TypeOf(types.QuestionType("")),

	"CHECKED_TYPES.int": reflect.TypeOf(types.Checked[int64]{}),
}
