// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type DistractorListClassView struct {
	inner baml.ClassBuilder
}

func (t *DistractorListClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DistractorListClassView) PropertyDistractors() (ClassPropertyView, error) {
	return t.inner.Property("distractors")
}

func (t *TypeBuilder) DistractorList() (*DistractorListClassView, error) {
	bld, err := t.inner.Class("DistractorList")
	if err != nil {
		return nil, err
	}
	return &DistractorListClassView{inner: bld}, nil
}

func (t *DistractorListClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GradeResultClassView struct {
	inner baml.ClassBuilder
}

func (t *GradeResultClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GradeResultClassView) PropertyRaw_score() (ClassPropertyView, error) {
	return t.inner.Property("raw_score")
}

func (t *GradeResultClassView) PropertyBand_code() (ClassPropertyView, error) {
	return t.inner.Property("band_code")
}

func (t *GradeResultClassView) PropertyReasoning() (ClassPropertyView, error) {
	return t.inner.Property("reasoning")
}

func (t *TypeBuilder) GradeResult() (*GradeResultClassView, error) {
	bld, err := t.inner.Class("GradeResult")
	if err != nil {
		return nil, err
	}
	return &GradeResultClassView{inner: bld}, nil
}

func (t *GradeResultClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RubricBandClassView struct {
	inner baml.ClassBuilder
}

func (t *RubricBandClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *RubricBandClassView) PropertyBand_code() (ClassPropertyView, error) {
	return t.inner.Property("band_code")
}

func (t *RubricBandClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *RubricBandClassView) PropertyMin_score() (ClassPropertyView, error) {
	return t.inner.Property("min_score")
}

func (t *RubricBandClassView) PropertyMax_score() (ClassPropertyView, error) {
	return t.inner.Property("max_score")
}

func (t *TypeBuilder) RubricBand() (*RubricBandClassView, error) {
	bld, err := t.inner.Class("RubricBand")
	if err != nil {
		return nil, err
	}
	return &RubricBandClassView{inner: bld}, nil
}

func (t *RubricBandClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RubricBandListClassView struct {
	inner baml.ClassBuilder
}

func (t *RubricBandListClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *RubricBandListClassView) PropertyBands() (ClassPropertyView, error) {
	return t.inner.Property("bands")
}

func (t *TypeBuilder) RubricBandList() (*RubricBandListClassView, error) {
	bld, err := t.inner.Class("RubricBandList")
	if err != nil {
		return nil, err
	}
	return &RubricBandListClassView{inner: bld}, nil
}

func (t *RubricBandListClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SuggestedItemClassView struct {
	inner baml.ClassBuilder
}

func (t *SuggestedItemClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SuggestedItemClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *SuggestedItemClassView) PropertyTitle() (ClassPropertyView, error) {
	return t.inner.Property("title")
}

func (t *SuggestedItemClassView) PropertyRequired() (ClassPropertyView, error) {
	return t.inner.Property("required")
}

func (t *SuggestedItemClassView) PropertyOptions() (ClassPropertyView, error) {
	return t.inner.Property("options")
}

func (t *TypeBuilder) SuggestedItem() (*SuggestedItemClassView, error) {
	bld, err := t.inner.Class("SuggestedItem")
	if err != nil {
		return nil, err
	}
	return &SuggestedItemClassView{inner: bld}, nil
}

func (t *SuggestedItemClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SuggestedItemListClassView struct {
	inner baml.ClassBuilder
}

func (t *SuggestedItemListClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SuggestedItemListClassView) PropertyItems() (ClassPropertyView, error) {
	return t.inner.Property("items")
}

func (t *TypeBuilder) SuggestedItemList() (*SuggestedItemListClassView, error) {
	bld, err := t.inner.Class("SuggestedItemList")
	if err != nil {
		return nil, err
	}
	return &SuggestedItemListClassView{inner: bld}, nil
}

func (t *SuggestedItemListClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
