// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type QuestionTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *QuestionTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *QuestionTypeEnumView) ValueSHORT_ANSWER() (EnumValueView, error) {
	return t.inner.Value("SHORT_ANSWER")
}

func (t *QuestionTypeEnumView) ValuePARAGRAPH() (EnumValueView, error) {
	return t.inner.Value("PARAGRAPH")
}

func (t *QuestionTypeEnumView) ValueMULTIPLE_CHOICE() (EnumValueView, error) {
	return t.inner.Value("MULTIPLE_CHOICE")
}

func (t *QuestionTypeEnumView) ValueYES_NO() (EnumValueView, error) {
	return t.inner.Value("YES_NO")
}

func (t *QuestionTypeEnumView) ValueLINEAR_SCALE() (EnumValueView, error) {
	return t.inner.Value("LINEAR_SCALE")
}

func (t *TypeBuilder) QuestionType() (*QuestionTypeEnumView, error) {
	bld, err := t.inner.Enum("QuestionType")
	if err != nil {
		return nil, err
	}
	return &QuestionTypeEnumView{inner: bld}, nil
}

func (t *QuestionTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}
