// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbauth

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type RoleAssignment struct {
	ID          int64
	UserID      int64
	Role        string
	ScopeNodeID sql.NullInt64
	CreatedAt   time.Time
}

type Session struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserAgent sql.NullString
	Ip        pqtype.Inet
	CreatedAt time.Time
}

type User struct {
	ID                 int64
	Email              string
	PasswordHash       string
	FullName           string
	Role               string
	MustChangePassword bool
	LockedAt           sql.NullTime
	FailedAttempts     int32
	LastLoginAt        sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          sql.NullTime
}
