// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_assignments.sql

package dbauth

import (
	"context"
	"database/sql"
)

const CreateRoleAssignment = `-- name: CreateRoleAssignment :exec
INSERT INTO role_assignments (user_id, role, scope_node_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role, COALESCE(scope_node_id, 0)) DO NOTHING
`

type CreateRoleAssignmentParams struct {
	UserID      int64
	Role        string
	ScopeNodeID sql.NullInt64
}

func (q *Queries) CreateRoleAssignment(ctx context.Context, arg CreateRoleAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, CreateRoleAssignment, arg.UserID, arg.Role, arg.ScopeNodeID)
	return err
}

const DeleteRoleAssignment = `-- name: DeleteRoleAssignment :exec
DELETE FROM role_assignments WHERE id = $1
`

func (q *Queries) DeleteRoleAssignment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteRoleAssignment, id)
	return err
}

const ListAllRoleAssignments = `-- name: ListAllRoleAssignments :many
SELECT id, user_id, role, scope_node_id, created_at
FROM role_assignments
ORDER BY user_id, created_at
`

func (q *Queries) ListAllRoleAssignments(ctx context.Context) ([]RoleAssignment, error) {
	rows, err := q.db.QueryContext(ctx, ListAllRoleAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleAssignment{}
	for rows.Next() {
		var i RoleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.ScopeNodeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRoleAssignmentsForUser = `-- name: ListRoleAssignmentsForUser :many
SELECT id, user_id, role, scope_node_id, created_at
FROM role_assignments
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListRoleAssignmentsForUser(ctx context.Context, userID int64) ([]RoleAssignment, error) {
	rows, err := q.db.QueryContext(ctx, ListRoleAssignmentsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleAssignment{}
	for rows.Next() {
		var i RoleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.ScopeNodeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
