// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbauth

import (
	"context"
	"time"
)

const CreateSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3, NULLIF($4, ''), NULLIF($5, '')::INET)
RETURNING id, user_id, token_hash, expires_at, revoked_at, user_agent, ip, created_at
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash []byte
	ExpiresAt time.Time
	Column4   interface{}
	Column5   interface{}
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, CreateSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Column4,
		arg.Column5,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const GetSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, user_agent, ip, created_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, GetSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const RevokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, RevokeAllSessionsForUser, userID)
	return err
}

const RevokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, RevokeSessionByID, id)
	return err
}

const RevokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, RevokeSessionByTokenHash, tokenHash)
	return err
}
