// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbauth

import (
	"context"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name, role, must_change_password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, full_name, role, must_change_password, locked_at, failed_attempts, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email              string
	PasswordHash       string
	FullName           string
	Role               string
	MustChangePassword bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, CreateUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.MustChangePassword,
		&i.LockedAt,
		&i.FailedAttempts,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, role, must_change_password, locked_at, failed_attempts, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE LOWER(email) = LOWER($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, GetUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.MustChangePassword,
		&i.LockedAt,
		&i.FailedAttempts,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, role, must_change_password, locked_at, failed_attempts, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.MustChangePassword,
		&i.LockedAt,
		&i.FailedAttempts,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, GetUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const IncrementFailedAttempts = `-- name: IncrementFailedAttempts :exec
UPDATE users
SET failed_attempts = failed_attempts + 1,
    locked_at       = CASE WHEN failed_attempts + 1 >= $2 THEN now() ELSE locked_at END,
    updated_at      = now()
WHERE id = $1
`

type IncrementFailedAttemptsParams struct {
	ID             int64
	FailedAttempts int32
}

func (q *Queries) IncrementFailedAttempts(ctx context.Context, arg IncrementFailedAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, IncrementFailedAttempts, arg.ID, arg.FailedAttempts)
	return err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, full_name, role, must_change_password, locked_at, failed_attempts, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY email
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, ListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.MustChangePassword,
			&i.LockedAt,
			&i.FailedAttempts,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ResetFailedAttempts = `-- name: ResetFailedAttempts :exec
UPDATE users
SET failed_attempts = 0,
    last_login_at   = now(),
    updated_at      = now()
WHERE id = $1
`

func (q *Queries) ResetFailedAttempts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, ResetFailedAttempts, id)
	return err
}

const UpdateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash        = $2,
    must_change_password = false,
    updated_at           = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, UpdateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
