// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package dbforms

import (
	"context"
	"database/sql"
	"encoding/json"
)

const CreateForm = `-- name: CreateForm :one
INSERT INTO forms (public_id, owner_id, title, description, settings)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, public_id, owner_id, title, description, status, settings, response_count, view_count, published_at, created_at, updated_at, deleted_at
`

type CreateFormParams struct {
	PublicID    string
	OwnerID     int64
	Title       string
	Description string
	Settings    json.RawMessage
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRowContext(ctx, CreateForm,
		arg.PublicID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Settings,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Settings,
		&i.ResponseCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const CreateFormVersion = `-- name: CreateFormVersion :one
INSERT INTO form_versions (form_id, version_num, title, description, snapshot)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, form_id, version_num, title, description, snapshot, published_at
`

type CreateFormVersionParams struct {
	FormID      int64
	VersionNum  int32
	Title       string
	Description string
	Snapshot    json.RawMessage
}

func (q *Queries) CreateFormVersion(ctx context.Context, arg CreateFormVersionParams) (FormVersion, error) {
	row := q.db.QueryRowContext(ctx, CreateFormVersion,
		arg.FormID,
		arg.VersionNum,
		arg.Title,
		arg.Description,
		arg.Snapshot,
	)
	var i FormVersion
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.VersionNum,
		&i.Title,
		&i.Description,
		&i.Snapshot,
		&i.PublishedAt,
	)
	return i, err
}

const CreateQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (form_id, client_id, sort_order, title, description, type, required, options, scale_min, scale_max, scale_labels, validation, grading, extra)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, form_id, client_id, sort_order, title, description, type, required, options, scale_min, scale_max, scale_labels, validation, grading, extra, image, translations, created_at, updated_at, deleted_at
`

type CreateQuestionParams struct {
	FormID      int64
	ClientID    string
	SortOrder   int32
	Title       string
	Description string
	Type        string
	Required    bool
	Options     json.RawMessage
	ScaleMin    sql.NullInt32
	ScaleMax    sql.NullInt32
	ScaleLabels json.RawMessage
	Validation  json.RawMessage
	Grading     json.RawMessage
	Extra       json.RawMessage
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, CreateQuestion,
		arg.FormID,
		arg.ClientID,
		arg.SortOrder,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Required,
		arg.Options,
		arg.ScaleMin,
		arg.ScaleMax,
		arg.ScaleLabels,
		arg.Validation,
		arg.Grading,
		arg.Extra,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ClientID,
		&i.SortOrder,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Required,
		&i.Options,
		&i.ScaleMin,
		&i.ScaleMax,
		&i.ScaleLabels,
		&i.Validation,
		&i.Grading,
		&i.Extra,
		&i.Image,
		&i.Translations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetFormByID = `-- name: GetFormByID :one
SELECT id, public_id, owner_id, title, description, status, settings, response_count, view_count, published_at, created_at, updated_at, deleted_at FROM forms WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFormByID(ctx context.Context, id int64) (Form, error) {
	row := q.db.QueryRowContext(ctx, GetFormByID, id)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Settings,
		&i.ResponseCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetFormByPublicID = `-- name: GetFormByPublicID :one
SELECT id, public_id, owner_id, title, description, status, settings, response_count, view_count, published_at, created_at, updated_at, deleted_at FROM forms WHERE public_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFormByPublicID(ctx context.Context, publicID string) (Form, error) {
	row := q.db.QueryRowContext(ctx, GetFormByPublicID, publicID)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Settings,
		&i.ResponseCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetFormVersion = `-- name: GetFormVersion :one
SELECT id, form_id, version_num, title, description, snapshot, published_at FROM form_versions WHERE id = $1
`

func (q *Queries) GetFormVersion(ctx context.Context, id int64) (FormVersion, error) {
	row := q.db.QueryRowContext(ctx, GetFormVersion, id)
	var i FormVersion
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.VersionNum,
		&i.Title,
		&i.Description,
		&i.Snapshot,
		&i.PublishedAt,
	)
	return i, err
}

const GetLatestFormVersion = `-- name: GetLatestFormVersion :one
SELECT id, form_id, version_num, title, description, snapshot, published_at FROM form_versions
WHERE form_id = $1
ORDER BY version_num DESC
LIMIT 1
`

func (q *Queries) GetLatestFormVersion(ctx context.Context, formID int64) (FormVersion, error) {
	row := q.db.QueryRowContext(ctx, GetLatestFormVersion, formID)
	var i FormVersion
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.VersionNum,
		&i.Title,
		&i.Description,
		&i.Snapshot,
		&i.PublishedAt,
	)
	return i, err
}

const GetQuestionByID = `-- name: GetQuestionByID :one
SELECT id, form_id, client_id, sort_order, title, description, type, required, options, scale_min, scale_max, scale_labels, validation, grading, extra, image, translations, created_at, updated_at, deleted_at FROM questions WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetQuestionByID(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRowContext(ctx, GetQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ClientID,
		&i.SortOrder,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Required,
		&i.Options,
		&i.ScaleMin,
		&i.ScaleMax,
		&i.ScaleLabels,
		&i.Validation,
		&i.Grading,
		&i.Extra,
		&i.Image,
		&i.Translations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ListFormVersions = `-- name: ListFormVersions :many
SELECT id, form_id, version_num, title, description, snapshot, published_at FROM form_versions WHERE form_id = $1 ORDER BY version_num DESC
`

func (q *Queries) ListFormVersions(ctx context.Context, formID int64) ([]FormVersion, error) {
	rows, err := q.db.QueryContext(ctx, ListFormVersions, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormVersion{}
	for rows.Next() {
		var i FormVersion
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.VersionNum,
			&i.Title,
			&i.Description,
			&i.Snapshot,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListFormsByOwner = `-- name: ListFormsByOwner :many
SELECT id, public_id, owner_id, title, description, status, settings, response_count, view_count, published_at, created_at, updated_at, deleted_at FROM forms
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListFormsByOwner(ctx context.Context, ownerID int64) ([]Form, error) {
	rows, err := q.db.QueryContext(ctx, ListFormsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Form{}
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Settings,
			&i.ResponseCount,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListQuestionsByForm = `-- name: ListQuestionsByForm :many
SELECT id, form_id, client_id, sort_order, title, description, type, required, options, scale_min, scale_max, scale_labels, validation, grading, extra, image, translations, created_at, updated_at, deleted_at FROM questions
WHERE form_id = $1 AND deleted_at IS NULL
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListQuestionsByForm(ctx context.Context, formID int64) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, ListQuestionsByForm, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ClientID,
			&i.SortOrder,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Required,
			&i.Options,
			&i.ScaleMin,
			&i.ScaleMax,
			&i.ScaleLabels,
			&i.Validation,
			&i.Grading,
			&i.Extra,
			&i.Image,
			&i.Translations,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeleteForm = `-- name: SoftDeleteForm :exec
UPDATE forms SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteForm(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, SoftDeleteForm, id)
	return err
}

const SoftDeleteQuestion = `-- name: SoftDeleteQuestion :exec
UPDATE questions SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteQuestion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, SoftDeleteQuestion, id)
	return err
}

const UpdateFormMeta = `-- name: UpdateFormMeta :one
UPDATE forms
SET title = $2, description = $3, settings = $4, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, public_id, owner_id, title, description, status, settings, response_count, view_count, published_at, created_at, updated_at, deleted_at
`

type UpdateFormMetaParams struct {
	ID          int64
	Title       string
	Description string
	Settings    json.RawMessage
}

func (q *Queries) UpdateFormMeta(ctx context.Context, arg UpdateFormMetaParams) (Form, error) {
	row := q.db.QueryRowContext(ctx, UpdateFormMeta,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Settings,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Settings,
		&i.ResponseCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const UpdateFormStatus = `-- name: UpdateFormStatus :one
UPDATE forms
SET status = $2, updated_at = now(),
    published_at = CASE WHEN $2 = 'published' THEN now() ELSE published_at END
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, public_id, owner_id, title, description, status, settings, response_count, view_count, published_at, created_at, updated_at, deleted_at
`

type UpdateFormStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateFormStatus(ctx context.Context, arg UpdateFormStatusParams) (Form, error) {
	row := q.db.QueryRowContext(ctx, UpdateFormStatus, arg.ID, arg.Status)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Settings,
		&i.ResponseCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const UpdateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET title = $2, description = $3, type = $4, required = $5,
    sort_order = $6, options = $7, scale_min = $8, scale_max = $9, scale_labels = $10,
    validation = $11, grading = $12, extra = $13, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, form_id, client_id, sort_order, title, description, type, required, options, scale_min, scale_max, scale_labels, validation, grading, extra, image, translations, created_at, updated_at, deleted_at
`

type UpdateQuestionParams struct {
	ID          int64
	Title       string
	Description string
	Type        string
	Required    bool
	SortOrder   int32
	Options     json.RawMessage
	ScaleMin    sql.NullInt32
	ScaleMax    sql.NullInt32
	ScaleLabels json.RawMessage
	Validation  json.RawMessage
	Grading     json.RawMessage
	Extra       json.RawMessage
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, UpdateQuestion,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Required,
		arg.SortOrder,
		arg.Options,
		arg.ScaleMin,
		arg.ScaleMax,
		arg.ScaleLabels,
		arg.Validation,
		arg.Grading,
		arg.Extra,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ClientID,
		&i.SortOrder,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Required,
		&i.Options,
		&i.ScaleMin,
		&i.ScaleMax,
		&i.ScaleLabels,
		&i.Validation,
		&i.Grading,
		&i.Extra,
		&i.Image,
		&i.Translations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
