// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbforms

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Form struct {
	ID            int64
	PublicID      string
	OwnerID       int64
	Title         string
	Description   string
	Status        string
	Settings      json.RawMessage
	ResponseCount int32
	ViewCount     int32
	PublishedAt   sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type FormVersion struct {
	ID          int64
	FormID      int64
	VersionNum  int32
	Title       string
	Description string
	Snapshot    json.RawMessage
	PublishedAt time.Time
}

type Question struct {
	ID           int64
	FormID       int64
	ClientID     string
	SortOrder    int32
	Title        string
	Description  string
	Type         string
	Required     bool
	Options      json.RawMessage
	ScaleMin     sql.NullInt32
	ScaleMax     sql.NullInt32
	ScaleLabels  json.RawMessage
	Validation   json.RawMessage
	Grading      json.RawMessage
	Extra        json.RawMessage
	Image        json.RawMessage
	Translations json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
