// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbnotifications

import (
	"database/sql"
	"encoding/json"
	"time"
)

type NotificationsOutbox struct {
	ID          int64
	Kind        string
	ToEmail     string
	ToName      sql.NullString
	Subject     string
	BodyHtml    string
	BodyText    string
	Status      string
	Attempts    int32
	LastError   sql.NullString
	ProviderID  sql.NullString
	Metadata    json.RawMessage
	ScheduledAt time.Time
	SentAt      sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
