// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package dbnotifications

import (
	"context"
	"database/sql"
	"encoding/json"
)

const EnqueueEmail = `-- name: EnqueueEmail :one
INSERT INTO notifications_outbox (kind, to_email, to_name, subject, body_html, body_text, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, kind, to_email, to_name, subject, body_html, body_text, status, attempts, last_error, provider_id, metadata, scheduled_at, sent_at, created_at, updated_at
`

type EnqueueEmailParams struct {
	Kind     string
	ToEmail  string
	ToName   sql.NullString
	Subject  string
	BodyHtml string
	BodyText string
	Metadata json.RawMessage
}

func (q *Queries) EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) (NotificationsOutbox, error) {
	row := q.db.QueryRowContext(ctx, EnqueueEmail,
		arg.Kind,
		arg.ToEmail,
		arg.ToName,
		arg.Subject,
		arg.BodyHtml,
		arg.BodyText,
		arg.Metadata,
	)
	var i NotificationsOutbox
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ToEmail,
		&i.ToName,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ProviderID,
		&i.Metadata,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetEmailByID = `-- name: GetEmailByID :one
SELECT id, kind, to_email, to_name, subject, body_html, body_text, status, attempts, last_error, provider_id, metadata, scheduled_at, sent_at, created_at, updated_at FROM notifications_outbox WHERE id = $1
`

func (q *Queries) GetEmailByID(ctx context.Context, id int64) (NotificationsOutbox, error) {
	row := q.db.QueryRowContext(ctx, GetEmailByID, id)
	var i NotificationsOutbox
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ToEmail,
		&i.ToName,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ProviderID,
		&i.Metadata,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListPending = `-- name: ListPending :many
SELECT id, kind, to_email, to_name, subject, body_html, body_text, status, attempts, last_error, provider_id, metadata, scheduled_at, sent_at, created_at, updated_at FROM notifications_outbox
WHERE status = 'pending' AND scheduled_at <= now()
ORDER BY scheduled_at
LIMIT $1
`

func (q *Queries) ListPending(ctx context.Context, limit int32) ([]NotificationsOutbox, error) {
	rows, err := q.db.QueryContext(ctx, ListPending, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationsOutbox{}
	for rows.Next() {
		var i NotificationsOutbox
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ToEmail,
			&i.ToName,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.ProviderID,
			&i.Metadata,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRecent = `-- name: ListRecent :many
SELECT id, kind, to_email, to_name, subject, body_html, body_text, status, attempts, last_error, provider_id, metadata, scheduled_at, sent_at, created_at, updated_at FROM notifications_outbox
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRecent(ctx context.Context, arg ListRecentParams) ([]NotificationsOutbox, error) {
	rows, err := q.db.QueryContext(ctx, ListRecent, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationsOutbox{}
	for rows.Next() {
		var i NotificationsOutbox
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ToEmail,
			&i.ToName,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.ProviderID,
			&i.Metadata,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkFailed = `-- name: MarkFailed :exec
UPDATE notifications_outbox
SET status = $2, last_error = $3, updated_at = now()
WHERE id = $1
`

type MarkFailedParams struct {
	ID        int64
	Status    string
	LastError sql.NullString
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.ExecContext(ctx, MarkFailed, arg.ID, arg.Status, arg.LastError)
	return err
}

const MarkSending = `-- name: MarkSending :exec
UPDATE notifications_outbox
SET status = 'sending', attempts = attempts + 1, updated_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkSending(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, MarkSending, id)
	return err
}

const MarkSent = `-- name: MarkSent :exec
UPDATE notifications_outbox
SET status = 'sent', provider_id = $2, sent_at = now(), updated_at = now()
WHERE id = $1
`

type MarkSentParams struct {
	ID         int64
	ProviderID sql.NullString
}

func (q *Queries) MarkSent(ctx context.Context, arg MarkSentParams) error {
	_, err := q.db.ExecContext(ctx, MarkSent, arg.ID, arg.ProviderID)
	return err
}
