// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type DistractorList struct {
	Distractors []string `json:"distractors"`
}

func (c *DistractorList) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "DistractorList" {
		panic(fmt.Sprintf("expected DistractorList, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "distractors":
			c.Distractors = baml.Decode(valueHolder).Interface().([]string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class DistractorList", key))

		}
	}

}

func (c DistractorList) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["distractors"] = c.Distractors

	return baml.EncodeClass("DistractorList", fields, nil)
}

func (c DistractorList) BamlTypeName() string {
	return "DistractorList"
}

type GradeResult struct {
	Raw_score Checked[int64] `json:"raw_score"`
	Band_code string         `json:"band_code"`
	Reasoning string         `json:"reasoning"`
}

func (c *GradeResult) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GradeResult" {
		panic(fmt.Sprintf("expected GradeResult, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "raw_score":
			c.Raw_score = baml.Decode(valueHolder).Interface().(Checked[int64])

		case "band_code":
			c.Band_code = baml.Decode(valueHolder).Interface().(string)

		case "reasoning":
			c.Reasoning = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GradeResult", key))

		}
	}

}

func (c GradeResult) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["raw_score"] = c.Raw_score

	fields["band_code"] = c.Band_code

	fields["reasoning"] = c.Reasoning

	return baml.EncodeClass("GradeResult", fields, nil)
}

func (c GradeResult) BamlTypeName() string {
	return "GradeResult"
}

type RubricBand struct {
	Band_code   string `json:"band_code"`
	Description string `json:"description"`
	Min_score   int64  `json:"min_score"`
	Max_score   int64  `json:"max_score"`
}

func (c *RubricBand) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "RubricBand" {
		panic(fmt.Sprintf("expected RubricBand, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "band_code":
			c.Band_code = baml.Decode(valueHolder).Interface().(string)

		case "description":
			c.Description = baml.Decode(valueHolder).Interface().(string)

		case "min_score":
			c.Min_score = baml.Decode(valueHolder).Int()

		case "max_score":
			c.Max_score = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class RubricBand", key))

		}
	}

}

func (c RubricBand) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["band_code"] = c.Band_code

	fields["description"] = c.Description

	fields["min_score"] = c.Min_score

	fields["max_score"] = c.Max_score

	return baml.EncodeClass("RubricBand", fields, nil)
}

func (c RubricBand) BamlTypeName() string {
	return "RubricBand"
}

type RubricBandList struct {
	Bands []RubricBand `json:"bands"`
}

func (c *RubricBandList) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "RubricBandList" {
		panic(fmt.Sprintf("expected RubricBandList, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "bands":
			c.Bands = baml.Decode(valueHolder).Interface().([]RubricBand)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class RubricBandList", key))

		}
	}

}

func (c RubricBandList) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["bands"] = c.Bands

	return baml.EncodeClass("RubricBandList", fields, nil)
}

func (c RubricBandList) BamlTypeName() string {
	return "RubricBandList"
}

type SuggestedItem struct {
	Type     QuestionType `json:"type"`
	Title    string       `json:"title"`
	Required bool         `json:"required"`
	Options  *[]string    `json:"options"`
}

func (c *SuggestedItem) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "SuggestedItem" {
		panic(fmt.Sprintf("expected SuggestedItem, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "type":
			c.Type = baml.Decode(valueHolder).Interface().(QuestionType)

		case "title":
			c.Title = baml.Decode(valueHolder).Interface().(string)

		case "required":
			c.Required = baml.Decode(valueHolder).Bool()

		case "options":
			c.Options = baml.Decode(valueHolder).Interface().(*[]string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class SuggestedItem", key))

		}
	}

}

func (c SuggestedItem) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["type"] = c.Type

	fields["title"] = c.Title

	fields["required"] = c.Required

	fields["options"] = c.Options

	return baml.EncodeClass("SuggestedItem", fields, nil)
}

func (c SuggestedItem) BamlTypeName() string {
	return "SuggestedItem"
}

type SuggestedItemList struct {
	Items []SuggestedItem `json:"items"`
}

func (c *SuggestedItemList) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "SuggestedItemList" {
		panic(fmt.Sprintf("expected SuggestedItemList, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "items":
			c.Items = baml.Decode(valueHolder).Interface().([]SuggestedItem)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class SuggestedItemList", key))

		}
	}

}

func (c SuggestedItemList) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["items"] = c.Items

	return baml.EncodeClass("SuggestedItemList", fields, nil)
}

func (c SuggestedItemList) BamlTypeName() string {
	return "SuggestedItemList"
}
