// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"encoding/json"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type QuestionType string

const (
	QuestionTypeSHORT_ANSWER    QuestionType = "SHORT_ANSWER"
	QuestionTypePARAGRAPH       QuestionType = "PARAGRAPH"
	QuestionTypeMULTIPLE_CHOICE QuestionType = "MULTIPLE_CHOICE"
	QuestionTypeYES_NO          QuestionType = "YES_NO"
	QuestionTypeLINEAR_SCALE    QuestionType = "LINEAR_SCALE"
)

// Values returns all allowed values for the QuestionType type.
func (QuestionType) Values() []QuestionType {
	return []QuestionType{
		QuestionTypeSHORT_ANSWER,
		QuestionTypePARAGRAPH,
		QuestionTypeMULTIPLE_CHOICE,
		QuestionTypeYES_NO,
		QuestionTypeLINEAR_SCALE,
	}
}

// IsValid checks whether the given QuestionType value is valid.
func (e QuestionType) IsValid() bool {

	for _, v := range e.Values() {
		if e == v {
			return true
		}
	}
	return false

}

// MarshalJSON customizes JSON marshaling for QuestionType.
func (e QuestionType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid QuestionType: %q", e)
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for QuestionType.
func (e *QuestionType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*e = QuestionType(s)
	if !e.IsValid() {
		return fmt.Errorf("invalid QuestionType: %q", s)
	}
	return nil
}

func (e *QuestionType) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
	name := holder.Name
	if name.Name != "QuestionType" && name.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected types.QuestionType, got %s.%s", string(name.Namespace.String()), string(name.Name)))
	}
	value := holder.Value
	*e = QuestionType(value)
}

func (e QuestionType) Encode() (*cffi.HostValue, error) {
	return baml.EncodeEnum("QuestionType", string(e), false)
}

func (e QuestionType) BamlTypeName() string {
	return "QuestionType"
}
