// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessment.sql

package dbassessment

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/lib/pq"
)

const BandForScore = `-- name: BandForScore :one
SELECT id, scale_code, ordinal, code, label, min_score, max_score FROM scale_bands
WHERE scale_code = $1 AND $2::int >= min_score AND $2::int <= max_score
ORDER BY ordinal DESC
LIMIT 1
`

type BandForScoreParams struct {
	ScaleCode string
	Column2   int32
}

func (q *Queries) BandForScore(ctx context.Context, arg BandForScoreParams) (ScaleBand, error) {
	row := q.db.QueryRowContext(ctx, BandForScore, arg.ScaleCode, arg.Column2)
	var i ScaleBand
	err := row.Scan(
		&i.ID,
		&i.ScaleCode,
		&i.Ordinal,
		&i.Code,
		&i.Label,
		&i.MinScore,
		&i.MaxScore,
	)
	return i, err
}

const CreateAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (campaign_id, student_id, access_token)
VALUES ($1, $2, $3)
RETURNING id, campaign_id, student_id, access_token, submitted_at, created_at
`

type CreateAssignmentParams struct {
	CampaignID  int64
	StudentID   int64
	AccessToken string
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, CreateAssignment, arg.CampaignID, arg.StudentID, arg.AccessToken)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.StudentID,
		&i.AccessToken,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const CreateCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (public_id, title, scale_code, form_id, form_version_id, period_id, scope_node_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, public_id, title, scale_code, form_id, form_version_id, period_id, scope_node_id, status, opens_at, closes_at, created_by, created_at, updated_at
`

type CreateCampaignParams struct {
	PublicID      string
	Title         string
	ScaleCode     string
	FormID        int64
	FormVersionID int64
	PeriodID      int64
	ScopeNodeID   int64
	Status        string
	CreatedBy     sql.NullInt64
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, CreateCampaign,
		arg.PublicID,
		arg.Title,
		arg.ScaleCode,
		arg.FormID,
		arg.FormVersionID,
		arg.PeriodID,
		arg.ScopeNodeID,
		arg.Status,
		arg.CreatedBy,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.ScaleCode,
		&i.FormID,
		&i.FormVersionID,
		&i.PeriodID,
		&i.ScopeNodeID,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateProctoredResponse = `-- name: CreateProctoredResponse :one
INSERT INTO responses (assignment_id, campaign_id, student_id, payload, proctored_by_user_id, entry_mode)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, assignment_id, campaign_id, student_id, payload, submitted_at, proctored_by_user_id, entry_mode
`

type CreateProctoredResponseParams struct {
	AssignmentID      int64
	CampaignID        int64
	StudentID         int64
	Payload           json.RawMessage
	ProctoredByUserID sql.NullInt64
	EntryMode         string
}

func (q *Queries) CreateProctoredResponse(ctx context.Context, arg CreateProctoredResponseParams) (Response, error) {
	row := q.db.QueryRowContext(ctx, CreateProctoredResponse,
		arg.AssignmentID,
		arg.CampaignID,
		arg.StudentID,
		arg.Payload,
		arg.ProctoredByUserID,
		arg.EntryMode,
	)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.CampaignID,
		&i.StudentID,
		&i.Payload,
		&i.SubmittedAt,
		&i.ProctoredByUserID,
		&i.EntryMode,
	)
	return i, err
}

const CreateResponse = `-- name: CreateResponse :one
INSERT INTO responses (assignment_id, campaign_id, student_id, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, assignment_id, campaign_id, student_id, payload, submitted_at, proctored_by_user_id, entry_mode
`

type CreateResponseParams struct {
	AssignmentID int64
	CampaignID   int64
	StudentID    int64
	Payload      json.RawMessage
}

func (q *Queries) CreateResponse(ctx context.Context, arg CreateResponseParams) (Response, error) {
	row := q.db.QueryRowContext(ctx, CreateResponse,
		arg.AssignmentID,
		arg.CampaignID,
		arg.StudentID,
		arg.Payload,
	)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.CampaignID,
		&i.StudentID,
		&i.Payload,
		&i.SubmittedAt,
		&i.ProctoredByUserID,
		&i.EntryMode,
	)
	return i, err
}

const CreateScore = `-- name: CreateScore :one
INSERT INTO scores (response_id, campaign_id, student_id, raw_score, band_code, band_ordinal)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, response_id, campaign_id, student_id, raw_score, band_code, band_ordinal, finalized_at
`

type CreateScoreParams struct {
	ResponseID  int64
	CampaignID  int64
	StudentID   int64
	RawScore    int32
	BandCode    string
	BandOrdinal int32
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error) {
	row := q.db.QueryRowContext(ctx, CreateScore,
		arg.ResponseID,
		arg.CampaignID,
		arg.StudentID,
		arg.RawScore,
		arg.BandCode,
		arg.BandOrdinal,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.ResponseID,
		&i.CampaignID,
		&i.StudentID,
		&i.RawScore,
		&i.BandCode,
		&i.BandOrdinal,
		&i.FinalizedAt,
	)
	return i, err
}

const DeleteResponseByAssignment = `-- name: DeleteResponseByAssignment :exec
DELETE FROM responses WHERE assignment_id = $1
`

func (q *Queries) DeleteResponseByAssignment(ctx context.Context, assignmentID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteResponseByAssignment, assignmentID)
	return err
}

const GetAssignmentByCampaignStudent = `-- name: GetAssignmentByCampaignStudent :one
SELECT id, campaign_id, student_id, access_token, submitted_at, created_at FROM assignments
WHERE campaign_id = $1 AND student_id = $2
`

type GetAssignmentByCampaignStudentParams struct {
	CampaignID int64
	StudentID  int64
}

func (q *Queries) GetAssignmentByCampaignStudent(ctx context.Context, arg GetAssignmentByCampaignStudentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, GetAssignmentByCampaignStudent, arg.CampaignID, arg.StudentID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.StudentID,
		&i.AccessToken,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetAssignmentByToken = `-- name: GetAssignmentByToken :one
SELECT id, campaign_id, student_id, access_token, submitted_at, created_at FROM assignments WHERE access_token = $1
`

func (q *Queries) GetAssignmentByToken(ctx context.Context, accessToken string) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, GetAssignmentByToken, accessToken)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.StudentID,
		&i.AccessToken,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetCampaignByID = `-- name: GetCampaignByID :one
SELECT id, public_id, title, scale_code, form_id, form_version_id, period_id, scope_node_id, status, opens_at, closes_at, created_by, created_at, updated_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id int64) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, GetCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.ScaleCode,
		&i.FormID,
		&i.FormVersionID,
		&i.PeriodID,
		&i.ScopeNodeID,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetCampaignByPublicID = `-- name: GetCampaignByPublicID :one
SELECT id, public_id, title, scale_code, form_id, form_version_id, period_id, scope_node_id, status, opens_at, closes_at, created_by, created_at, updated_at FROM campaigns WHERE public_id = $1
`

func (q *Queries) GetCampaignByPublicID(ctx context.Context, publicID string) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, GetCampaignByPublicID, publicID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.ScaleCode,
		&i.FormID,
		&i.FormVersionID,
		&i.PeriodID,
		&i.ScopeNodeID,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetScale = `-- name: GetScale :one
SELECT code, label, created_at FROM scales WHERE code = $1
`

func (q *Queries) GetScale(ctx context.Context, code string) (Scale, error) {
	row := q.db.QueryRowContext(ctx, GetScale, code)
	var i Scale
	err := row.Scan(&i.Code, &i.Label, &i.CreatedAt)
	return i, err
}

const GetScoreByResponse = `-- name: GetScoreByResponse :one
SELECT id, response_id, campaign_id, student_id, raw_score, band_code, band_ordinal, finalized_at FROM scores WHERE response_id = $1
`

func (q *Queries) GetScoreByResponse(ctx context.Context, responseID int64) (Score, error) {
	row := q.db.QueryRowContext(ctx, GetScoreByResponse, responseID)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.ResponseID,
		&i.CampaignID,
		&i.StudentID,
		&i.RawScore,
		&i.BandCode,
		&i.BandOrdinal,
		&i.FinalizedAt,
	)
	return i, err
}

const ListAssignmentsByCampaign = `-- name: ListAssignmentsByCampaign :many
SELECT id, campaign_id, student_id, access_token, submitted_at, created_at FROM assignments WHERE campaign_id = $1 ORDER BY id
`

func (q *Queries) ListAssignmentsByCampaign(ctx context.Context, campaignID int64) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, ListAssignmentsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.StudentID,
			&i.AccessToken,
			&i.SubmittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListBandsForScale = `-- name: ListBandsForScale :many
SELECT id, scale_code, ordinal, code, label, min_score, max_score FROM scale_bands WHERE scale_code = $1 ORDER BY ordinal ASC
`

func (q *Queries) ListBandsForScale(ctx context.Context, scaleCode string) ([]ScaleBand, error) {
	rows, err := q.db.QueryContext(ctx, ListBandsForScale, scaleCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScaleBand{}
	for rows.Next() {
		var i ScaleBand
		if err := rows.Scan(
			&i.ID,
			&i.ScaleCode,
			&i.Ordinal,
			&i.Code,
			&i.Label,
			&i.MinScore,
			&i.MaxScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCampaignsByScope = `-- name: ListCampaignsByScope :many
SELECT id, public_id, title, scale_code, form_id, form_version_id, period_id, scope_node_id, status, opens_at, closes_at, created_by, created_at, updated_at FROM campaigns
WHERE scope_node_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCampaignsByScope(ctx context.Context, scopeNodeID int64) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, ListCampaignsByScope, scopeNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.ScaleCode,
			&i.FormID,
			&i.FormVersionID,
			&i.PeriodID,
			&i.ScopeNodeID,
			&i.Status,
			&i.OpensAt,
			&i.ClosesAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListGradingRosterRows = `-- name: ListGradingRosterRows :many
SELECT
    cs.student_id::bigint        AS student_id,
    a.id                         AS assignment_id,
    s.id                         AS score_id,
    s.raw_score                  AS raw_score,
    s.band_code                  AS band_code,
    s.band_ordinal               AS band_ordinal,
    r.entry_mode                 AS entry_mode,
    r.submitted_at               AS submitted_at,
    r.proctored_by_user_id       AS proctored_by_user_id
FROM unnest($2::bigint[]) AS cs(student_id)
LEFT JOIN assignments a ON a.campaign_id = $1 AND a.student_id = cs.student_id
LEFT JOIN scores s      ON s.campaign_id = $1 AND s.student_id = cs.student_id
LEFT JOIN responses r   ON r.id = (SELECT id FROM responses WHERE campaign_id = $1 AND student_id = cs.student_id ORDER BY id DESC LIMIT 1)
ORDER BY cs.student_id
`

type ListGradingRosterRowsParams struct {
	CampaignID int64
	StudentIds []int64
}

type ListGradingRosterRowsRow struct {
	StudentID         int64
	AssignmentID      sql.NullInt64
	ScoreID           sql.NullInt64
	RawScore          sql.NullInt32
	BandCode          sql.NullString
	BandOrdinal       sql.NullInt32
	EntryMode         sql.NullString
	SubmittedAt       sql.NullTime
	ProctoredByUserID sql.NullInt64
}

func (q *Queries) ListGradingRosterRows(ctx context.Context, arg ListGradingRosterRowsParams) ([]ListGradingRosterRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListGradingRosterRows, arg.CampaignID, pq.Array(arg.StudentIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGradingRosterRowsRow{}
	for rows.Next() {
		var i ListGradingRosterRowsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.AssignmentID,
			&i.ScoreID,
			&i.RawScore,
			&i.BandCode,
			&i.BandOrdinal,
			&i.EntryMode,
			&i.SubmittedAt,
			&i.ProctoredByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOpenCampaignsWithScores = `-- name: ListOpenCampaignsWithScores :many
SELECT DISTINCT c.id, c.period_id, c.scope_node_id, c.scale_code
FROM campaigns c
JOIN scores s ON s.campaign_id = c.id
WHERE c.status = 'open'
`

type ListOpenCampaignsWithScoresRow struct {
	ID          int64
	PeriodID    int64
	ScopeNodeID int64
	ScaleCode   string
}

func (q *Queries) ListOpenCampaignsWithScores(ctx context.Context) ([]ListOpenCampaignsWithScoresRow, error) {
	rows, err := q.db.QueryContext(ctx, ListOpenCampaignsWithScores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenCampaignsWithScoresRow{}
	for rows.Next() {
		var i ListOpenCampaignsWithScoresRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.ScopeNodeID,
			&i.ScaleCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListResponsesByCampaign = `-- name: ListResponsesByCampaign :many
SELECT id, assignment_id, campaign_id, student_id, payload, submitted_at, proctored_by_user_id, entry_mode FROM responses WHERE campaign_id = $1 ORDER BY submitted_at DESC
`

func (q *Queries) ListResponsesByCampaign(ctx context.Context, campaignID int64) ([]Response, error) {
	rows, err := q.db.QueryContext(ctx, ListResponsesByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Response{}
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.CampaignID,
			&i.StudentID,
			&i.Payload,
			&i.SubmittedAt,
			&i.ProctoredByUserID,
			&i.EntryMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListScales = `-- name: ListScales :many
SELECT code, label, created_at FROM scales ORDER BY code
`

func (q *Queries) ListScales(ctx context.Context) ([]Scale, error) {
	rows, err := q.db.QueryContext(ctx, ListScales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scale{}
	for rows.Next() {
		var i Scale
		if err := rows.Scan(&i.Code, &i.Label, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListScoredStudentIDs = `-- name: ListScoredStudentIDs :many
SELECT DISTINCT student_id FROM scores WHERE campaign_id = $1
`

func (q *Queries) ListScoredStudentIDs(ctx context.Context, campaignID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, ListScoredStudentIDs, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var student_id int64
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListScoresByCampaign = `-- name: ListScoresByCampaign :many
SELECT id, response_id, campaign_id, student_id, raw_score, band_code, band_ordinal, finalized_at FROM scores WHERE campaign_id = $1 ORDER BY band_ordinal DESC, raw_score DESC
`

func (q *Queries) ListScoresByCampaign(ctx context.Context, campaignID int64) ([]Score, error) {
	rows, err := q.db.QueryContext(ctx, ListScoresByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Score{}
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.ResponseID,
			&i.CampaignID,
			&i.StudentID,
			&i.RawScore,
			&i.BandCode,
			&i.BandOrdinal,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkAssignmentSubmitted = `-- name: MarkAssignmentSubmitted :one
UPDATE assignments
SET submitted_at = now()
WHERE id = $1 AND submitted_at IS NULL
RETURNING id, campaign_id, student_id, access_token, submitted_at, created_at
`

func (q *Queries) MarkAssignmentSubmitted(ctx context.Context, id int64) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, MarkAssignmentSubmitted, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.StudentID,
		&i.AccessToken,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const UpdateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET status = $2,
    opens_at = CASE WHEN $2 = 'open' AND opens_at IS NULL THEN now() ELSE opens_at END,
    closes_at = CASE WHEN $2 = 'closed' THEN now() ELSE closes_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, title, scale_code, form_id, form_version_id, period_id, scope_node_id, status, opens_at, closes_at, created_by, created_at, updated_at
`

type UpdateCampaignStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, UpdateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.ScaleCode,
		&i.FormID,
		&i.FormVersionID,
		&i.PeriodID,
		&i.ScopeNodeID,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
