// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbassessment

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Assignment struct {
	ID          int64
	CampaignID  int64
	StudentID   int64
	AccessToken string
	SubmittedAt sql.NullTime
	CreatedAt   time.Time
}

type Campaign struct {
	ID            int64
	PublicID      string
	Title         string
	ScaleCode     string
	FormID        int64
	FormVersionID int64
	PeriodID      int64
	ScopeNodeID   int64
	Status        string
	OpensAt       sql.NullTime
	ClosesAt      sql.NullTime
	CreatedBy     sql.NullInt64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Response struct {
	ID                int64
	AssignmentID      int64
	CampaignID        int64
	StudentID         int64
	Payload           json.RawMessage
	SubmittedAt       time.Time
	ProctoredByUserID sql.NullInt64
	EntryMode         string
}

type Scale struct {
	Code      string
	Label     string
	CreatedAt time.Time
}

type ScaleBand struct {
	ID        int64
	ScaleCode string
	Ordinal   int32
	Code      string
	Label     string
	MinScore  int32
	MaxScore  int32
}

type Score struct {
	ID          int64
	ResponseID  int64
	CampaignID  int64
	StudentID   int64
	RawScore    int32
	BandCode    string
	BandOrdinal int32
	FinalizedAt time.Time
}
